import { browser } from '$app/environment';
import { base } from '$app/paths';

/**
 * Frontend loader for the Image Pipeline v2 sidecar manifest
 * (PRD-018 / RFC-022 §7).
 *
 * Reads static/data/image-vision.json (machine-generated by
 * scripts/score-images.ts at build time) and exposes a tiny lookup
 * API for hero / card / thumbnail components. Joins to
 * static/data/image-provenance.json (ADR-047) by image path — the
 * sidecar never modifies the provenance manifest; this layer composes
 * the two at runtime for the frontend.
 *
 * Frontend integration pattern (used by gallery + hero + thumb
 * components):
 *
 *   const img = getImage('static/images/missions/curiosity-hero.jpg');
 *   <img src={pickVariant(img, 'hero', isMobile)} alt={img?.subject} />
 *
 * Backward-compatible: getImage() returns undefined for paths not in
 * the manifest. Callers fall back to the source path so v1 image
 * surfaces keep working before v2 has scored everything.
 */

export type VariantRatio = '1x1' | '4x3' | '16x9';

export type VisionCategory =
  | 'spacecraft'
  | 'surface'
  | 'launch'
  | 'orbital'
  | 'hardware'
  | 'people'
  | 'diagram'
  | 'render'
  | 'other';

export type RejectedBy =
  | null
  | 'score-below-threshold'
  | 'category-people'
  | 'category-diagram'
  | 'human';

export interface ImageVisionEntry {
  score: number;
  subject: string;
  category: VisionCategory;
  focal_point: { x: number; y: number };
  variants: Record<VariantRatio, string>;
  rejected_by: RejectedBy;
  fallback: boolean;
  scored_at: string;
  scoring_cost_usd: number;
}

export interface ImageVisionManifest {
  version: number;
  generated_at: string;
  vision_provider: string;
  vision_model: string;
  prompt_version: string;
  entries: Record<string, ImageVisionEntry>;
}

let cached: ImageVisionManifest | null = null;
let loadPromise: Promise<ImageVisionManifest> | null = null;

/**
 * Load + cache the manifest. Soft-fail on fetch error — absent
 * manifest = empty entries, all callers fall back to source path.
 * SSR-safe (returns empty manifest on the server; the actual
 * fetched data hydrates on the client).
 */
export function loadImageVisionManifest(): Promise<ImageVisionManifest> {
  if (cached) return Promise.resolve(cached);
  if (loadPromise) return loadPromise;
  if (!browser) {
    cached = emptyManifest();
    return Promise.resolve(cached);
  }
  loadPromise = fetch(`${base}/data/image-vision.json`)
    .then((r) => (r.ok ? (r.json() as Promise<ImageVisionManifest>) : emptyManifest()))
    .catch(() => emptyManifest())
    .then((m) => {
      cached = m;
      loadPromise = null;
      return m;
    });
  return loadPromise;
}

/**
 * Get a vision entry for an image path. Synchronous — only returns
 * an entry once the manifest has been loaded (via
 * loadImageVisionManifest). Used by hot paths that can't await on
 * every render.
 */
export function getImageEntry(imagePath: string): ImageVisionEntry | undefined {
  return cached?.entries[imagePath];
}

/**
 * Variant selection by surface use case + viewport. Used by hero,
 * card, and thumbnail components to pick the right pre-cropped file.
 *
 *   hero          → 16:9 on desktop, 4:3 on mobile
 *   card          → 4:3 always (gallery card grid)
 *   thumbnail     → 1:1 always (mobile thumbnail row / fleet gallery)
 *   full          → source path (lightbox / full-screen)
 */
export type ImageSurface = 'hero' | 'card' | 'thumbnail' | 'full';

export function pickVariant(
  entry: ImageVisionEntry | undefined,
  surface: ImageSurface,
  isMobile = false,
): string | undefined {
  if (!entry || surface === 'full') return undefined;
  const variants = entry.variants;
  switch (surface) {
    case 'thumbnail':
      return variants['1x1'] || undefined;
    case 'card':
      return variants['4x3'] || undefined;
    case 'hero':
      return (isMobile ? variants['4x3'] : variants['16x9']) || undefined;
  }
}

/**
 * Compute the CSS `object-position` value for a surface that uses
 * `object-fit: cover` with the source image (no pre-crop variant).
 * The vision focal-point becomes the centre of attention.
 */
export function focalToObjectPosition(entry: ImageVisionEntry | undefined): string {
  if (!entry) return 'center';
  const x = Math.max(0, Math.min(100, entry.focal_point.x * 100));
  const y = Math.max(0, Math.min(100, entry.focal_point.y * 100));
  return `${x.toFixed(1)}% ${y.toFixed(1)}%`;
}

/**
 * For test seams + diagnostics. Resets the in-memory cache so the
 * next loadImageVisionManifest() call hits the network again.
 */
export function _resetImageVisionCache(): void {
  cached = null;
  loadPromise = null;
}

function emptyManifest(): ImageVisionManifest {
  return {
    version: 1,
    generated_at: new Date(0).toISOString(),
    vision_provider: 'none',
    vision_model: 'none',
    prompt_version: 'none',
    entries: {},
  };
}
