/**
 * Link provenance client (ADR-051 Milestone L-B).
 *
 * `static/data/link-provenance.json` is generated by
 * `scripts/build-link-provenance.ts` and carries TASL-equivalent data
 * for every outbound LEARN link rendered by the app. The `LinkCredit`
 * component reads it to render the source/language/last-verified
 * footer under each anchor; the public `/library` page (Milestone L-D)
 * reads it directly.
 *
 * Lives in its own module (rather than `$lib/data.ts`) because outbound
 * LEARN-link discipline is a distinct concern from the per-entity data
 * surfaces (missions, planets, sites, etc.) and the contract may
 * grow — for example the L-E link-checker is going to want to refresh
 * `last_verified` against this manifest.
 */
import { base } from '$app/paths';

const LINK_PROVENANCE_URL_PATH = 'link-provenance.json';

export type LinkTier = 'intro' | 'core' | 'deep';
export type LinkKind =
  | 'agency-official'
  | 'mission-microsite'
  | 'science-publisher'
  | 'encyclopedic'
  | 'educational'
  | 'community'
  | 'vendor-official';

export interface LinkProvenanceEntry {
  id: string;
  entity_id: string;
  category: string;
  route: string;
  url: string;
  label: string;
  tier: LinkTier;
  source_id: string;
  language: string;
  kind: LinkKind;
  fair_use_rationale: string;
  last_verified: string;
  replaced_with?: string | null;
  notes?: string | null;
}

export interface LinkProvenanceManifest {
  schema_version: number;
  generated_at: string;
  script_version: string;
  commit_sha: string | null;
  entries: LinkProvenanceEntry[];
}

let manifest: LinkProvenanceManifest | null = null;
let byKey: Map<string, LinkProvenanceEntry> | null = null;

export async function getLinkProvenanceManifest(): Promise<LinkProvenanceManifest | null> {
  if (manifest) return manifest;
  try {
    const res = await fetch(`${base}/data/${LINK_PROVENANCE_URL_PATH}`);
    if (!res.ok) return null;
    const m = (await res.json()) as LinkProvenanceManifest;
    manifest = m;
    byKey = new Map(m.entries.map((e) => [`${e.entity_id}__${e.url}`, e]));
    return m;
  } catch {
    return null;
  }
}

/**
 * Returns the provenance entry for a link rendered by panel/route code.
 * Caller passes the *raw* author-time URL it bound to `<a href>`; this
 * helper canonicalises (mirroring scripts/build-link-provenance.ts) and
 * looks up by `(entity_id, canonical_url)`. Returns null when the
 * manifest is absent or the link is not recorded — caller renders a
 * minimal credit-less anchor.
 */
export async function getLinkProvenance(
  entityId: string,
  url: string,
): Promise<LinkProvenanceEntry | null> {
  const m = await getLinkProvenanceManifest();
  if (!m || !byKey) return null;
  const canonical = canonicaliseLinkUrl(url);
  return byKey.get(`${entityId}__${canonical}`) ?? null;
}

const TRACKER_PARAMS = new Set([
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_term',
  'utm_content',
  'utm_id',
  'fbclid',
  'gclid',
  'mc_cid',
  'mc_eid',
  '_ga',
]);

/**
 * URL canonicalisation — mirrors scripts/build-link-provenance.ts so a
 * raw `<a href>` lookup matches the manifest key. Strips utm_*, fbclid,
 * gclid, mc_cid, mc_eid, _ga; AMP suffix; m. mobile prefix on common
 * encyclopedic / agency hosts; and the URL fragment.
 */
export function canonicaliseLinkUrl(raw: string): string {
  try {
    const u = new URL(raw);
    if (u.hostname.startsWith('m.')) {
      const rest = u.hostname.slice(2);
      if (/^(wikipedia|wikimedia|nasa|esa|jaxa|isro|cnsa|roscosmos)\./i.test(rest)) {
        u.hostname = rest;
      }
    }
    if (u.pathname.endsWith('/amp') || u.pathname.endsWith('/amp/')) {
      u.pathname = u.pathname.replace(/\/amp\/?$/, '');
    }
    const drop: string[] = [];
    for (const [k] of u.searchParams) {
      if (TRACKER_PARAMS.has(k.toLowerCase())) drop.push(k);
    }
    for (const k of drop) u.searchParams.delete(k);
    u.hash = '';
    return u.toString();
  } catch {
    return raw;
  }
}

/** Test-only: clear the in-memory cache. */
export function __resetLinkProvenanceCache(): void {
  manifest = null;
  byKey = null;
}
