/**
 * Spacecraft anatomy manifest. Every craft's anatomy is now a generated
 * watercolor cutaway / pencil sketch raster under `/images/anatomy/{id}.webp`
 * (#367) — the legacy hand-drawn SVG schematics were retired. The id set is
 * DERIVED from the webp files on disk (`anatomy-ids.json`, regenerated by
 * scripts/build-anatomy-webp.mjs) so adding art never needs a hand-edit.
 *
 * The ANATOMY/DETAIL tab on /fleet + the station-module panels render the
 * image via a plain <img>; /colophon shows the same set as thumbnails.
 */
import { assetOrigin } from './asset-url';
import anatomyIds from './anatomy-ids.json';
import explodedIds from './anatomy-exploded-ids.json';

export const SPACECRAFT_ANATOMY_IMG = new Set<string>(anatomyIds);

/**
 * Station-visitor panels (/iss, /tiangong) key modules by underscore ids
 * while /fleet uses kebab ids. Map the underscore id to the kebab webp so a
 * single illustration serves both surfaces.
 */
const ANATOMY_ALIAS: Record<string, string> = {
  crew_dragon: 'crew-dragon',
  cargo_dragon: 'cargo-dragon-2',
  soyuz_ms: 'soyuz-ms',
  progress_ms: 'progress-ms',
  cygnus: 'cygnus-enhanced',
  'cygnus-standard': 'cygnus-enhanced',
  htv_x: 'htv-x',
};

export function spacecraftDiagramPath(id: string): string | null {
  if (SPACECRAFT_ANATOMY_IMG.has(id)) return `${assetOrigin}/images/anatomy/${id}.webp`;
  const alias = ANATOMY_ALIAS[id];
  if (alias && SPACECRAFT_ANATOMY_IMG.has(alias))
    return `${assetOrigin}/images/anatomy/${alias}.webp`;
  return null;
}

// Launcher exploded-stage cutaways (PRD-032 follow-up). A richer companion to
// the pencil anatomy — watercolor exploded view showing stages, engines, tanks,
// boosters + payload. Derived from anatomy-exploded-ids.json (regenerated by
// the resize step in the launcher-cutaway pipeline).
export const LAUNCHER_CUTAWAY_IMG = new Set<string>(explodedIds);

export function launcherCutawayPath(id: string): string | null {
  return LAUNCHER_CUTAWAY_IMG.has(id) ? `${assetOrigin}/images/anatomy-exploded/${id}.webp` : null;
}
