/**
 * Video provenance client (PRD-031 / RFC-033, S0).
 *
 * `static/data/video-provenance.json` is generated by
 * `scripts/build-video-provenance.ts` from the curated
 * `static/data/video-sources.json`. It carries per-clip attribution + fair-use
 * for every video Orrery LINKS (never hosts). The MediaPlayer facade reads it
 * to render a click-to-load embed; galleries read it to interleave videos with
 * stills; `/credits` + `/colophon` read it to disclose provenance.
 *
 * Lives in its own module (rather than `$lib/data.ts`) for the same reason
 * link-provenance does: linked-not-hosted media is a distinct concern from the
 * per-entity data surfaces, and the contract (link-checker refreshing
 * `last_verified`, live-feed pins) will grow.
 */
import { base } from '$app/paths';

const VIDEO_PROVENANCE_URL_PATH = 'video-provenance.json';

export type VideoProvider = 'youtube' | 'vimeo' | 'agency-hls' | 'agency-mp4';
export type VideoKind =
  | 'launch'
  | 'landing'
  | 'edl'
  | 'milestone'
  | 'accident'
  | 'rollout'
  | 'broadcast-archive'
  | 'animation'
  | 'live';
export type VideoEntityKind = 'mission' | 'launch-site' | 'fleet' | 'landing-site' | 'live-pin';
export type ContentAdvisory = 'loss-of-life' | 'graphic' | null;

export interface VideoProvenanceEntry {
  id: string;
  entity_id: string;
  entity_kind: VideoEntityKind;
  provider: VideoProvider;
  provider_ref: string;
  source_url: string;
  channel: string;
  agency: string;
  title: string;
  caption: string | null;
  kind: VideoKind;
  poster: string | null;
  duration_seconds: number | null;
  start_seconds: number;
  license_or_fair_use: string;
  content_advisory: ContentAdvisory;
  last_verified: string;
  notes: string | null;
}

export interface VideoProvenanceManifest {
  schema_version: number;
  generated_at: string;
  script_version: string;
  commit_sha: string | null;
  entries: VideoProvenanceEntry[];
}

let manifest: VideoProvenanceManifest | null = null;
let byId: Map<string, VideoProvenanceEntry> | null = null;
let byEntity: Map<string, VideoProvenanceEntry[]> | null = null;

function index(m: VideoProvenanceManifest): void {
  byId = new Map(m.entries.map((e) => [e.id, e]));
  byEntity = new Map();
  for (const e of m.entries) {
    const list = byEntity.get(e.entity_id);
    if (list) list.push(e);
    else byEntity.set(e.entity_id, [e]);
  }
}

export async function getVideoManifest(): Promise<VideoProvenanceManifest | null> {
  if (manifest) return manifest;
  try {
    const res = await fetch(`${base}/data/${VIDEO_PROVENANCE_URL_PATH}`);
    if (!res.ok) return null;
    const m = (await res.json()) as VideoProvenanceManifest;
    manifest = m;
    index(m);
    return m;
  } catch {
    return null;
  }
}

/** Resolve a single clip by its manifest id (the `videos:[{id}]` entity ref). */
export async function getVideo(id: string): Promise<VideoProvenanceEntry | null> {
  const m = await getVideoManifest();
  if (!m || !byId) return null;
  return byId.get(id) ?? null;
}

/** All clips owned by an entity, in manifest order. Empty when none/absent. */
export async function getVideosForEntity(entityId: string): Promise<VideoProvenanceEntry[]> {
  const m = await getVideoManifest();
  if (!m || !byEntity) return [];
  return byEntity.get(entityId) ?? [];
}

/**
 * Build the privacy-preserving embed URL for a clip. Cookie-less variants, no
 * autoplay + no recommendations chrome where the provider allows suppressing
 * it. The MediaPlayer facade appends `autoplay=1` (and focus) only on the
 * user click that mounts the embed — never here.
 *
 * For agency-hls / agency-mp4 the provider_ref IS the media URL (returned
 * as-is); the facade feeds it to a <video> element.
 */
export function embedUrlFor(entry: VideoProvenanceEntry): string {
  const start = entry.start_seconds > 0 ? entry.start_seconds : 0;
  switch (entry.provider) {
    case 'youtube': {
      // cc_load_policy=1 auto-shows captions when the source provides them
      // (RFC-033 §5 a11y — the caption path for linked, not-hosted video).
      const q = new URLSearchParams({
        rel: '0',
        modestbranding: '1',
        playsinline: '1',
        cc_load_policy: '1',
      });
      if (start) q.set('start', String(start));
      // encodeURIComponent neutralises any injection via provider_ref (a valid
      // 11-char id is unchanged); build-video-provenance also validates it.
      return `https://www.youtube-nocookie.com/embed/${encodeURIComponent(entry.provider_ref)}?${q.toString()}`;
    }
    case 'vimeo': {
      const q = new URLSearchParams({ dnt: '1' });
      const hash = start ? `#t=${start}s` : '';
      return `https://player.vimeo.com/video/${encodeURIComponent(entry.provider_ref)}?${q.toString()}${hash}`;
    }
    case 'agency-hls':
    case 'agency-mp4':
      // Only ever hand an absolute https URL to <video src> (defense-in-depth
      // against a javascript:/relative provider_ref; build validates too).
      return /^https:\/\//.test(entry.provider_ref) ? entry.provider_ref : '';
  }
}

/**
 * Poster still for the click-to-load facade tile. Prefers a hosted PD/CC
 * poster (RFC-033 open Q2); falls back to the provider thumbnail for the long
 * tail (a plain <img> CDN fetch, no cookies, lazy-loaded — never an iframe).
 * Returns null when there is nothing to show → the tile renders a gradient
 * placeholder behind the play affordance.
 */
export function posterUrlFor(entry: VideoProvenanceEntry): string | null {
  if (entry.poster) return `${base}${entry.poster}`;
  if (entry.provider === 'youtube') {
    return `https://i.ytimg.com/vi/${entry.provider_ref}/hqdefault.jpg`;
  }
  return null;
}

/** Test-only: drop the module-singleton cache. */
export function __resetVideoProvenanceCache(): void {
  manifest = null;
  byId = null;
  byEntity = null;
}
