<script lang="ts">
  /*
    /colophon — bill-of-materials for Orrery's ORIGINAL content: every
    diagram, 3D model, chart, icon, and piece of writing the project draws
    in code or hand-authors. The counterpart to /credits, which attributes
    REUSED third-party material.

    Data: static/data/original-work.json (generated by
    scripts/build-original-work.mjs). Loaded client-side in an $effect so
    the relative fetch never runs during prerender.
  */
  import { base } from '$app/paths';
  import * as m from '$lib/paraglide/messages';
  import { getLocale } from '$lib/paraglide/runtime';
  import { getAudioProvenanceManifest } from '$lib/data';
  import { ICON_SHOWCASE } from '$lib/components/icons';

  type Diagram = { title: string; file: string; cover: boolean };
  type Item = { title: string; what: string; where: string; route: string; thumb?: string };
  type Manifest = {
    anatomy_art: Diagram[];
    diagrams_science: Diagram[];
    models3d: Item[];
    canvas2d: Item[];
    ui: Item[];
    writing: Item[];
  };
  // Tour episodes (#358 follow-up) — original scripts live here on the
  // colophon, not /credits. Two contributions: the written script
  // (transcript) and the synthesized audio (listen).
  type Episode = { id: string; title: string; route: string; txt: string; mp3: string };

  let data = $state<Manifest | null>(null);
  let episodes = $state<Episode[]>([]);
  let lightbox = $state<{ src: string; title: string; route: string } | null>(null);

  $effect(() => {
    void fetch(`${base}/data/original-work.json`)
      .then((r) => r.json())
      .then((j: Manifest) => {
        data = j;
      })
      .catch(() => {
        data = null;
      });

    void getAudioProvenanceManifest()
      .then((mft) => {
        if (!mft) return;
        const loc = getLocale();
        const rows = mft.entries.filter((e) => e.locale === loc);
        const use = rows.length ? rows : mft.entries.filter((e) => e.locale === 'en-US');
        const byId = new Map<string, Episode>();
        for (const e of use) {
          if (byId.has(e.episode_id) || !e.path_txt) continue;
          byId.set(e.episode_id, {
            id: e.episode_id,
            title: e.title ?? e.episode_id,
            route: e.route ?? '/',
            txt: e.path_txt,
            mp3: e.path_mp3 ?? '',
          });
        }
        episodes = [...byId.values()];
      })
      .catch(() => {});
  });
</script>

<svelte:head>
  <title>{m.colophon_title()} — Orrery</title>
</svelte:head>

<section class="colophon" aria-labelledby="colophon-title" data-route-ready="true">
  <header class="head">
    <h1 id="colophon-title">{m.colophon_title()}</h1>
    <p class="intro">{m.colophon_intro()}</p>
    <p class="attribution">{m.colophon_attribution()}</p>
    <p class="reused">
      <a href="{base}/credits">{m.colophon_reused_link()} →</a>
    </p>
  </header>

  {#if !data}
    <p class="loading">…</p>
  {:else}
    <!-- Showpiece: generated watercolor cutaways + pencil sketches (#367). -->
    <section class="block" aria-labelledby="sec-cutaways">
      <h2 id="sec-cutaways">
        {m.colophon_section_cutaways()}<span class="count">{data.anatomy_art.length}</span>
      </h2>
      <ul class="thumb-grid wide">
        {#each data.anatomy_art as d (d.file)}
          <li class="thumb-card">
            <button
              type="button"
              class="thumb-open"
              onclick={() =>
                (lightbox = { src: `${base}${d.file}`, title: d.title, route: '/fleet' })}
            >
              <img src="{base}{d.file}" alt={d.title} loading="lazy" decoding="async" />
            </button>
            <span class="thumb-title">{d.title}</span>
          </li>
        {/each}
      </ul>
    </section>

    <!-- Hand-authored SVG diagrams: real thumbnails. -->
    <section class="block" aria-labelledby="sec-diagrams">
      <h2 id="sec-diagrams">
        {m.colophon_section_diagrams()}<span class="count">{data.diagrams_science.length}</span>
      </h2>
      <ul class="thumb-grid">
        {#each data.diagrams_science as d (d.file)}
          <li class="thumb-card" class:cover={d.cover}>
            <button
              type="button"
              class="thumb-open"
              onclick={() =>
                (lightbox = { src: `${base}${d.file}`, title: d.title, route: '/science' })}
            >
              <img src="{base}{d.file}" alt={d.title} loading="lazy" decoding="async" />
            </button>
            <span class="thumb-title">{d.title}</span>
          </li>
        {/each}
      </ul>
    </section>

    <!-- Live-rendered geometry/canvas: no static preview, link to the route. -->
    {#each [{ id: 'models', label: m.colophon_section_models(), items: data.models3d }, { id: 'canvas', label: m.colophon_section_canvas(), items: data.canvas2d }] as sec (sec.id)}
      <section class="block" aria-labelledby="sec-{sec.id}">
        <h2 id="sec-{sec.id}">{sec.label}<span class="count">{sec.items.length}</span></h2>
        <ul class="item-list">
          {#each sec.items as it (it.title)}
            <li class="item" class:has-thumb={it.thumb}>
              {#if it.thumb}
                <button
                  type="button"
                  class="thumb-open it-thumb"
                  onclick={() =>
                    (lightbox = { src: `${base}${it.thumb}`, title: it.title, route: it.route })}
                >
                  <img src="{base}{it.thumb}" alt={it.title} loading="lazy" decoding="async" />
                </button>
              {/if}
              <p class="it-title">{it.title}</p>
              <p class="it-what">{it.what}</p>
              <a class="it-where" href="{base}{it.route}">{m.colophon_seen_on()} {it.where} →</a>
            </li>
          {/each}
        </ul>
      </section>
    {/each}

    <!-- Interface graphics: every original UI glyph, embedded as the real
         inline SVG from the icon registry (crisp, theme-coloured) rather
         than a rasterised preview. -->
    <section class="block" aria-labelledby="sec-ui">
      <h2 id="sec-ui">
        {m.colophon_section_ui()}<span class="count">{ICON_SHOWCASE.length}</span>
      </h2>
      <ul class="icon-grid">
        {#each ICON_SHOWCASE as icon (icon.id)}
          <li class="icon-card">
            <div class="icon-swatch">
              {#each icon.variants ?? [{ props: {} }] as v (v.label ?? 'only')}
                <span class="icon-variant">
                  <icon.component {...v.props} />
                  {#if v.label}<span class="iv-label">{v.label}</span>{/if}
                </span>
              {/each}
            </div>
            <p class="it-title">{icon.label}</p>
            <p class="it-what">{icon.what}</p>
            <a class="it-where" href="{base}{icon.route}">{m.colophon_seen_on()} {icon.where} →</a>
          </li>
        {/each}
      </ul>
    </section>

    <section class="block" aria-labelledby="sec-writing">
      <h2 id="sec-writing">
        {m.colophon_section_writing()}<span class="count">{data.writing.length}</span>
      </h2>
      <ul class="item-list">
        {#each data.writing as it (it.title)}
          <li class="item">
            <p class="it-title">{it.title}</p>
            <p class="it-what">{it.what}</p>
            <a class="it-where" href="{base}{it.route}">{m.colophon_seen_on()} {it.where} →</a>
          </li>
        {/each}
      </ul>
    </section>

    {#if episodes.length > 0}
      <section class="block" aria-labelledby="sec-tours">
        <h2 id="sec-tours">
          {m.colophon_section_tours()}<span class="count">{episodes.length}</span>
        </h2>
        <p class="tours-note">{m.colophon_tours_note()}</p>
        <ul class="episode-list">
          {#each episodes as ep (ep.id)}
            <li class="episode">
              <span class="ep-title">{ep.title}</span>
              <span class="ep-actions">
                <a
                  class="ep-action script"
                  href="{base}{ep.txt}"
                  target="_blank"
                  rel="noopener noreferrer"
                  download
                >
                  ↓ {m.colophon_transcript()}
                </a>
                {#if ep.mp3}
                  <a
                    class="ep-action audio"
                    href="{base}{ep.mp3}"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    ▶ {m.colophon_listen()}
                  </a>
                {/if}
              </span>
            </li>
          {/each}
        </ul>
      </section>
    {/if}
  {/if}
</section>

{#if lightbox}
  <button
    type="button"
    class="lightbox"
    onclick={() => (lightbox = null)}
    aria-label={m.colophon_close_aria()}
  >
    <figure>
      <img src={lightbox.src} alt={lightbox.title} />
      <figcaption>
        <span class="lb-title">{lightbox.title}</span>
        <a class="lb-route" href="{base}{lightbox.route}"
          >{m.colophon_seen_on()} {lightbox.route} →</a
        >
      </figcaption>
    </figure>
  </button>
{/if}

<style>
  .colophon {
    max-width: 1100px;
    margin: 0 auto;
    padding: 48px 20px 96px;
    color: rgba(255, 255, 255, 0.85);
  }
  .head {
    margin-bottom: 40px;
  }
  h1 {
    font-family: 'Bebas Neue', sans-serif;
    font-size: 44px;
    letter-spacing: 3px;
    margin: 0 0 12px;
    color: #fff;
  }
  .intro {
    font-size: 15px;
    line-height: 1.6;
    max-width: 720px;
    color: rgba(255, 255, 255, 0.78);
    margin: 0 0 10px;
  }
  .attribution {
    font-family: 'Space Mono', monospace;
    font-size: 12px;
    color: rgba(201, 170, 111, 0.85);
    margin: 0 0 8px;
  }
  .reused a {
    font-size: 13px;
    color: rgba(255, 255, 255, 0.7);
    border-bottom: 1px dotted rgba(255, 255, 255, 0.4);
    text-decoration: none;
  }
  .loading {
    color: rgba(255, 255, 255, 0.4);
    font-family: 'Space Mono', monospace;
  }

  .block {
    margin-top: 40px;
  }
  .block h2 {
    font-family: 'Bebas Neue', sans-serif;
    font-size: 24px;
    letter-spacing: 2px;
    color: #fff;
    margin: 0 0 16px;
    display: flex;
    align-items: baseline;
    gap: 10px;
  }
  .count {
    font-family: 'Space Mono', monospace;
    font-size: 12px;
    letter-spacing: 0;
    color: rgba(255, 255, 255, 0.4);
  }

  .thumb-grid {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 14px;
  }
  /* Detailed cutaway art reads better at a larger thumbnail. */
  .thumb-grid.wide {
    grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
  }
  .thumb-grid.wide .thumb-card img {
    aspect-ratio: 3 / 2;
  }
  .thumb-card {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 4px;
    padding: 10px;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .thumb-open {
    display: block;
    width: 100%;
    padding: 0;
    border: 0;
    background: none;
    cursor: zoom-in;
  }
  .thumb-card img {
    width: 100%;
    aspect-ratio: 4 / 3;
    object-fit: contain;
    background: rgba(0, 0, 0, 0.25);
    border-radius: 3px;
  }
  .thumb-card.cover img {
    aspect-ratio: 16 / 9;
  }
  .thumb-title {
    font-size: 12px;
    color: rgba(255, 255, 255, 0.7);
    line-height: 1.35;
  }

  .item-list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 16px;
  }
  .item {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 4px;
    padding: 14px 16px;
    overflow: hidden;
  }
  .item.has-thumb {
    padding-top: 0;
  }
  .it-thumb {
    margin: 0 -16px 12px;
    display: block;
    width: calc(100% + 32px);
    border: 0;
    padding: 0;
    background: #11151a;
    cursor: zoom-in;
  }
  .it-thumb img {
    width: 100%;
    aspect-ratio: 16 / 10;
    object-fit: cover;
    display: block;
  }
  .it-title {
    font-weight: 600;
    color: #fff;
    margin: 0 0 6px;
    font-size: 14px;
  }
  .it-what {
    font-size: 13px;
    line-height: 1.5;
    color: rgba(255, 255, 255, 0.7);
    margin: 0 0 10px;
  }
  .it-where {
    font-family: 'Space Mono', monospace;
    font-size: 11px;
    color: rgba(255, 255, 255, 0.55);
    text-decoration: none;
    border-bottom: 1px dotted rgba(255, 255, 255, 0.3);
  }

  /* Interface-graphics grid — the real inline SVGs on a faint glow swatch. */
  .icon-grid {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    gap: 16px;
  }
  .icon-card {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 4px;
    overflow: hidden;
  }
  .icon-swatch {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-end;
    gap: 16px;
    padding: 22px 16px;
    min-height: 78px;
    color: #5eead4;
    background: radial-gradient(circle at 50% 36%, rgba(94, 234, 212, 0.1), transparent 70%);
  }
  .icon-variant {
    display: inline-flex;
    flex-direction: column;
    align-items: center;
    gap: 7px;
  }
  .iv-label {
    font-family: 'Space Mono', monospace;
    font-size: 8.5px;
    letter-spacing: 0.5px;
    text-transform: uppercase;
    color: rgba(255, 255, 255, 0.4);
  }
  .icon-card .it-title,
  .icon-card .it-what {
    padding-left: 16px;
    padding-right: 16px;
  }
  .icon-card .it-title {
    margin-top: 12px;
  }
  .icon-card .it-where {
    margin: 0 16px 14px;
    display: inline-block;
  }

  .tours-note {
    font-size: 13px;
    line-height: 1.55;
    color: rgba(255, 255, 255, 0.6);
    max-width: 720px;
    margin: 0 0 16px;
  }
  .episode-list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
    gap: 4px 24px;
  }
  .episode {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 9px 0;
    border-bottom: 1px solid rgba(255, 255, 255, 0.06);
  }
  .ep-title {
    flex: 1;
    font-size: 13px;
    line-height: 1.35;
    color: rgba(255, 255, 255, 0.85);
  }
  /* Stack the two chips vertically — that frees the row width so the title
     can run to two lines instead of truncating. */
  .ep-actions {
    display: flex;
    flex-direction: column;
    gap: 4px;
    flex-shrink: 0;
  }
  .ep-action {
    font-family: 'Space Mono', monospace;
    font-size: 10px;
    letter-spacing: 0.5px;
    text-decoration: none;
    padding: 2px 8px;
    border-radius: 3px;
    border: 1px solid transparent;
    white-space: nowrap;
    text-align: center;
  }
  /* Two contributions, two accents: script = gold, audio = teal. */
  .ep-action.script {
    color: rgba(201, 170, 111, 0.95);
    border-color: rgba(201, 170, 111, 0.35);
    background: rgba(201, 170, 111, 0.08);
  }
  .ep-action.script:hover {
    background: rgba(201, 170, 111, 0.16);
  }
  .ep-action.audio {
    color: #4ecdc4;
    border-color: rgba(78, 205, 196, 0.35);
    background: rgba(78, 205, 196, 0.08);
  }
  .ep-action.audio:hover {
    background: rgba(78, 205, 196, 0.16);
  }

  /* Full-size lightbox (#367). */
  .lightbox {
    position: fixed;
    inset: 0;
    z-index: 200;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 4vmin;
    border: 0;
    background: rgba(4, 7, 10, 0.92);
    cursor: zoom-out;
  }
  .lightbox figure {
    margin: 0;
    max-width: 96vw;
    max-height: 92vh;
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .lightbox img {
    max-width: 100%;
    max-height: 84vh;
    object-fit: contain;
    border-radius: 4px;
  }
  .lightbox figcaption {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    gap: 16px;
    flex-wrap: wrap;
  }
  .lb-title {
    font-family: 'Bebas Neue', sans-serif;
    font-size: 20px;
    letter-spacing: 1.5px;
    color: #fff;
  }
  .lb-route {
    font-family: 'Space Mono', monospace;
    font-size: 12px;
    color: #4ecdc4;
    text-decoration: none;
    border-bottom: 1px dotted rgba(78, 205, 196, 0.5);
  }
</style>
