<script lang="ts">
  /*
    /colophon — bill-of-materials for Orrery's ORIGINAL content: every
    diagram, 3D model, chart, icon, and piece of writing the project draws
    in code or hand-authors. The counterpart to /credits, which attributes
    REUSED third-party material.

    Data: static/data/original-work.json (generated by
    scripts/build-original-work.mjs). Loaded client-side in an $effect so
    the relative fetch never runs during prerender.
  */
  import { base } from '$app/paths';
  import * as m from '$lib/paraglide/messages';
  import { getLocale } from '$lib/paraglide/runtime';
  import { getAudioProvenanceManifest } from '$lib/data';

  type Diagram = { title: string; file: string; cover: boolean };
  type Item = { title: string; what: string; where: string; route: string };
  type Manifest = {
    anatomy_art: Diagram[];
    diagrams_science: Diagram[];
    models3d: Item[];
    canvas2d: Item[];
    ui: Item[];
    writing: Item[];
  };
  // Tour episodes (#358 follow-up) — original scripts live here on the
  // colophon, not /credits. Each links to its transcript.
  type Episode = { id: string; title: string; route: string; txt: string };

  let data = $state<Manifest | null>(null);
  let episodes = $state<Episode[]>([]);

  $effect(() => {
    void fetch(`${base}/data/original-work.json`)
      .then((r) => r.json())
      .then((j: Manifest) => {
        data = j;
      })
      .catch(() => {
        data = null;
      });

    void getAudioProvenanceManifest()
      .then((mft) => {
        if (!mft) return;
        const loc = getLocale();
        const rows = mft.entries.filter((e) => e.locale === loc);
        const use = rows.length ? rows : mft.entries.filter((e) => e.locale === 'en-US');
        const byId = new Map<string, Episode>();
        for (const e of use) {
          if (byId.has(e.episode_id) || !e.path_txt) continue;
          byId.set(e.episode_id, {
            id: e.episode_id,
            title: e.title ?? e.episode_id,
            route: e.route ?? '/',
            txt: e.path_txt,
          });
        }
        episodes = [...byId.values()];
      })
      .catch(() => {});
  });
</script>

<svelte:head>
  <title>{m.colophon_title()} — Orrery</title>
</svelte:head>

<section class="colophon" aria-labelledby="colophon-title" data-route-ready="true">
  <header class="head">
    <h1 id="colophon-title">{m.colophon_title()}</h1>
    <p class="intro">{m.colophon_intro()}</p>
    <p class="attribution">{m.colophon_attribution()}</p>
    <p class="reused">
      <a href="{base}/credits">{m.colophon_reused_link()} →</a>
    </p>
  </header>

  {#if !data}
    <p class="loading">…</p>
  {:else}
    <!-- Showpiece: generated watercolor cutaways + pencil sketches (#367). -->
    <section class="block" aria-labelledby="sec-cutaways">
      <h2 id="sec-cutaways">
        {m.colophon_section_cutaways()}<span class="count">{data.anatomy_art.length}</span>
      </h2>
      <ul class="thumb-grid wide">
        {#each data.anatomy_art as d (d.file)}
          <li class="thumb-card">
            <img src="{base}{d.file}" alt={d.title} loading="lazy" decoding="async" />
            <span class="thumb-title">{d.title}</span>
          </li>
        {/each}
      </ul>
    </section>

    <!-- Hand-authored SVG diagrams: real thumbnails. -->
    <section class="block" aria-labelledby="sec-diagrams">
      <h2 id="sec-diagrams">
        {m.colophon_section_diagrams()}<span class="count">{data.diagrams_science.length}</span>
      </h2>
      <ul class="thumb-grid">
        {#each data.diagrams_science as d (d.file)}
          <li class="thumb-card" class:cover={d.cover}>
            <img src="{base}{d.file}" alt={d.title} loading="lazy" decoding="async" />
            <span class="thumb-title">{d.title}</span>
          </li>
        {/each}
      </ul>
    </section>

    <!-- Live-rendered geometry/canvas: no static preview, link to the route. -->
    {#each [{ id: 'models', label: m.colophon_section_models(), items: data.models3d }, { id: 'canvas', label: m.colophon_section_canvas(), items: data.canvas2d }, { id: 'ui', label: m.colophon_section_ui(), items: data.ui }] as sec (sec.id)}
      <section class="block" aria-labelledby="sec-{sec.id}">
        <h2 id="sec-{sec.id}">{sec.label}<span class="count">{sec.items.length}</span></h2>
        <ul class="item-list">
          {#each sec.items as it (it.title)}
            <li class="item">
              <p class="it-title">{it.title}</p>
              <p class="it-what">{it.what}</p>
              <a class="it-where" href="{base}{it.route}">{m.colophon_seen_on()} {it.where} →</a>
            </li>
          {/each}
        </ul>
      </section>
    {/each}

    <section class="block" aria-labelledby="sec-writing">
      <h2 id="sec-writing">
        {m.colophon_section_writing()}<span class="count">{data.writing.length}</span>
      </h2>
      <ul class="item-list">
        {#each data.writing as it (it.title)}
          <li class="item">
            <p class="it-title">{it.title}</p>
            <p class="it-what">{it.what}</p>
            <a class="it-where" href="{base}{it.route}">{m.colophon_seen_on()} {it.where} →</a>
          </li>
        {/each}
      </ul>
    </section>

    {#if episodes.length > 0}
      <section class="block" aria-labelledby="sec-tours">
        <h2 id="sec-tours">
          {m.colophon_section_tours()}<span class="count">{episodes.length}</span>
        </h2>
        <p class="tours-note">{m.colophon_tours_note()}</p>
        <ul class="episode-list">
          {#each episodes as ep (ep.id)}
            <li class="episode">
              <a class="ep-title" href="{base}{ep.txt}" target="_blank" rel="noopener noreferrer">
                {ep.title}
              </a>
              <a class="ep-route" href="{base}{ep.route}"><code>{ep.route}</code></a>
            </li>
          {/each}
        </ul>
      </section>
    {/if}
  {/if}
</section>

<style>
  .colophon {
    max-width: 1100px;
    margin: 0 auto;
    padding: 48px 20px 96px;
    color: rgba(255, 255, 255, 0.85);
  }
  .head {
    margin-bottom: 40px;
  }
  h1 {
    font-family: 'Bebas Neue', sans-serif;
    font-size: 44px;
    letter-spacing: 3px;
    margin: 0 0 12px;
    color: #fff;
  }
  .intro {
    font-size: 15px;
    line-height: 1.6;
    max-width: 720px;
    color: rgba(255, 255, 255, 0.78);
    margin: 0 0 10px;
  }
  .attribution {
    font-family: 'Space Mono', monospace;
    font-size: 12px;
    color: rgba(201, 170, 111, 0.85);
    margin: 0 0 8px;
  }
  .reused a {
    font-size: 13px;
    color: rgba(255, 255, 255, 0.7);
    border-bottom: 1px dotted rgba(255, 255, 255, 0.4);
    text-decoration: none;
  }
  .loading {
    color: rgba(255, 255, 255, 0.4);
    font-family: 'Space Mono', monospace;
  }

  .block {
    margin-top: 40px;
  }
  .block h2 {
    font-family: 'Bebas Neue', sans-serif;
    font-size: 24px;
    letter-spacing: 2px;
    color: #fff;
    margin: 0 0 16px;
    display: flex;
    align-items: baseline;
    gap: 10px;
  }
  .count {
    font-family: 'Space Mono', monospace;
    font-size: 12px;
    letter-spacing: 0;
    color: rgba(255, 255, 255, 0.4);
  }

  .thumb-grid {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 14px;
  }
  /* Detailed cutaway art reads better at a larger thumbnail. */
  .thumb-grid.wide {
    grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
  }
  .thumb-grid.wide .thumb-card img {
    aspect-ratio: 3 / 2;
  }
  .thumb-card {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 4px;
    padding: 10px;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .thumb-card img {
    width: 100%;
    aspect-ratio: 4 / 3;
    object-fit: contain;
    background: rgba(0, 0, 0, 0.25);
    border-radius: 3px;
  }
  .thumb-card.cover img {
    aspect-ratio: 16 / 9;
  }
  .thumb-title {
    font-size: 12px;
    color: rgba(255, 255, 255, 0.7);
    line-height: 1.35;
  }

  .item-list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 16px;
  }
  .item {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 4px;
    padding: 14px 16px;
  }
  .it-title {
    font-weight: 600;
    color: #fff;
    margin: 0 0 6px;
    font-size: 14px;
  }
  .it-what {
    font-size: 13px;
    line-height: 1.5;
    color: rgba(255, 255, 255, 0.7);
    margin: 0 0 10px;
  }
  .it-where {
    font-family: 'Space Mono', monospace;
    font-size: 11px;
    color: rgba(255, 255, 255, 0.55);
    text-decoration: none;
    border-bottom: 1px dotted rgba(255, 255, 255, 0.3);
  }

  .tours-note {
    font-size: 13px;
    line-height: 1.55;
    color: rgba(255, 255, 255, 0.6);
    max-width: 720px;
    margin: 0 0 16px;
  }
  .episode-list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
    gap: 4px 24px;
  }
  .episode {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    gap: 12px;
    padding: 7px 0;
    border-bottom: 1px solid rgba(255, 255, 255, 0.06);
  }
  .ep-title {
    font-size: 13px;
    color: rgba(255, 255, 255, 0.85);
    text-decoration: none;
    border-bottom: 1px dotted rgba(255, 255, 255, 0.35);
  }
  .ep-title:hover {
    color: #fff;
  }
  .ep-route {
    text-decoration: none;
    flex-shrink: 0;
  }
  .ep-route code {
    font-family: 'Space Mono', monospace;
    font-size: 10px;
    color: rgba(255, 255, 255, 0.4);
  }
</style>
