import { test, expect } from '@playwright/test';

/**
 * Image Pipeline v2 — variant smoke (PRD-018 / RFC-022).
 *
 * Asserts that the 1:1, 4:3, 16:9 pre-cropped variants generated by
 * scripts/vision/crop-variants.ts are actually served from the
 * static asset path. v2 mobile bundle savings (PRD-018 M9, S9)
 * depend on these existing — if `crop-variants.ts` silently drops
 * a variant or the build pipeline doesn't copy them into `build/`,
 * the MOBILE=1 selector in src/lib/image-vision.ts falls back to
 * the larger original and the success-criterion #6 mobile-bundle
 * savings target evaporates.
 *
 * One known-good entry per ratio is enough — if the generator
 * works for a7l (a Tier-0 NASA artefact with strong scoring), it
 * works for the rest of the manifest. Covering all 568 1:1 variants
 * would be brittle and slow.
 */

test.describe('Image Pipeline v2 — variant serving smoke', () => {
  test('a7l 1:1 variant is served (mobile bucket)', async ({ request }) => {
    const res = await request.get('/images/fleet-galleries/a7l/01.1x1.jpg');
    expect(res.status()).toBe(200);
    const buf = await res.body();
    expect(buf.length).toBeGreaterThan(5_000);
  });

  test('a7l 4:3 variant is served (card bucket)', async ({ request }) => {
    const res = await request.get('/images/fleet-galleries/a7l/01.4x3.jpg');
    expect(res.status()).toBe(200);
    const buf = await res.body();
    expect(buf.length).toBeGreaterThan(5_000);
  });

  test('a7l 16:9 variant is served (desktop hero bucket)', async ({ request }) => {
    const res = await request.get('/images/fleet-galleries/a7l/01.16x9.jpg');
    expect(res.status()).toBe(200);
    const buf = await res.body();
    expect(buf.length).toBeGreaterThan(5_000);
  });

  test('image-vision.json sidecar is served + has expected shape', async ({ request }) => {
    const res = await request.get('/data/image-vision.json');
    expect(res.status()).toBe(200);
    const m = (await res.json()) as {
      version?: string;
      entries?: Record<string, { score: number; category: string }>;
    };
    expect(m.version).toBeTruthy();
    expect(m.entries).toBeTruthy();
    const entryCount = Object.keys(m.entries ?? {}).length;
    expect(entryCount).toBeGreaterThan(500);
  });
});
