import { test, expect } from '@playwright/test';

/**
 * Image Pipeline v2 — variant smoke (PRD-018 / RFC-022).
 *
 * Asserts that the 1:1 pre-cropped variant generated by
 * scripts/vision/crop-variants.ts is actually served from the
 * static asset path. v2 mobile bundle savings (PRD-018 M9, S9)
 * depend on this existing — if `crop-variants.ts` silently drops
 * the variant or the build pipeline doesn't copy them into `build/`,
 * the MOBILE=1 selector in src/lib/image-vision.ts falls back to
 * the larger original and the success-criterion #6 mobile-bundle
 * savings target evaporates.
 *
 * One known-good entry is enough — if the generator works for a7l
 * (a Tier-0 NASA artefact with strong scoring), it works for the
 * rest of the manifest. Covering all 568 1:1 variants would be
 * brittle and slow.
 *
 * 4:3 / 16:9 variants were dropped in the post-#5 image-pipeline-v2
 * restructure (2026-06-12) — the runtime now picks between original
 * and the 1:1 mobile bucket only. Tests for those ratios were
 * removed with that change.
 */

test.describe('Image Pipeline v2 — variant serving smoke', () => {
  test('a7l 1:1 variant is served (mobile bucket)', async ({ request }) => {
    const res = await request.get('/images/fleet-galleries/a7l/01.1x1.jpg');
    expect(res.status()).toBe(200);
    const buf = await res.body();
    expect(buf.length).toBeGreaterThan(5_000);
  });

  test('image-vision.json sidecar is served + has expected shape', async ({ request }) => {
    const res = await request.get('/data/image-vision.json');
    expect(res.status()).toBe(200);
    const m = (await res.json()) as {
      version?: number;
      entries?: Record<string, { score: number; category: string }>;
    };
    expect(m.version).toBeDefined();
    expect(typeof m.entries).toBe('object');
    expect(m.entries).not.toBeNull();
    const entryCount = Object.keys(m.entries ?? {}).length;
    expect(entryCount).toBeGreaterThan(500);
  });
});
