/**
 * Fetches external assets at build time per ADR-016.
 *
 * Slice 1: Google Fonts (Bebas Neue, Space Mono, Crimson Pro).
 * Slice 3: planet textures + moon texture from Solar System Scope.
 * v0.1.x patches: agency logos from Wikimedia Commons.
 * Future: NASA Images API for per-mission imagery; rocket reference imagery.
 *
 * Run via: npm run fetch-assets
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';

// ──────────────────────────────────────────────────────────────────────
// FONTS — Slice 1
// ──────────────────────────────────────────────────────────────────────

interface FontDef {
  family: string;
  cssParam: string;
}

const FONTS: FontDef[] = [
  { family: 'Bebas Neue', cssParam: 'Bebas+Neue' },
  { family: 'Space Mono', cssParam: 'Space+Mono:wght@400;700' },
  { family: 'Crimson Pro', cssParam: 'Crimson+Pro:ital,wght@0,400;0,600;1,400' },
];

const FONT_BASE_URL = 'https://fonts.googleapis.com/css2';
// User-Agent that triggers woff2 responses from Google Fonts.
const FONT_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FONTS_DIR = 'static/fonts';
const FONTS_CSS_OUT = 'src/lib/styles/fonts.css';

async function fetchFontCss(font: FontDef): Promise<string> {
  const url = `${FONT_BASE_URL}?family=${font.cssParam}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': FONT_UA } });
  if (!res.ok) throw new Error(`Failed to fetch CSS for ${font.family}: HTTP ${res.status}`);
  return res.text();
}

function extractWoff2Urls(css: string): Set<string> {
  const urls = new Set<string>();
  const regex = /url\((https:\/\/[^)]+\.woff2)\)/g;
  let match;
  while ((match = regex.exec(css)) !== null) {
    urls.add(match[1]);
  }
  return urls;
}

async function fetchFonts(): Promise<number> {
  await mkdir(FONTS_DIR, { recursive: true });
  await mkdir(dirname(FONTS_CSS_OUT), { recursive: true });

  let combinedCss =
    '/* Auto-generated by scripts/fetch-assets.ts. Do not edit by hand.\n' +
    '   Re-run with: npm run fetch-assets */\n\n';
  let downloaded = 0;

  for (const font of FONTS) {
    console.log(`  ${font.family}…`);
    const css = await fetchFontCss(font);
    const urls = extractWoff2Urls(css);

    let localCss = css;
    for (const url of urls) {
      const filename = url.split('/').pop();
      if (!filename) throw new Error(`Could not derive filename from ${url}`);
      const localPath = join(FONTS_DIR, filename);
      await downloadFile(url, localPath);
      localCss = localCss.replaceAll(url, `/fonts/${filename}`);
      downloaded++;
    }

    combinedCss += `/* ${font.family} */\n${localCss}\n`;
  }

  await writeFile(FONTS_CSS_OUT, combinedCss);
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// PLANET + MOON TEXTURES — Slice 3
//
// Source: Solar System Scope (https://www.solarsystemscope.com/textures/)
// Licence: CC BY 4.0. Attribution: "Solar System Scope" in mission-credits page.
// 2K resolution chosen as a balance of detail and bundle size (~3 MB total).
// Issue #3 originally pointed at three.js's r128 examples/textures/planets/
// folder, which doesn't actually contain 2k_*.jpg files in r128 — only Earth
// and Moon textures. SSS is the canonical source for the full set.
// ──────────────────────────────────────────────────────────────────────

const TEXTURE_BASE_URL = 'https://www.solarsystemscope.com/textures/download';

const TEXTURES = [
  '2k_sun.jpg',
  '2k_mercury.jpg',
  '2k_venus_atmosphere.jpg',
  '2k_earth_daymap.jpg',
  '2k_mars.jpg',
  '2k_jupiter.jpg',
  '2k_saturn.jpg',
  '2k_uranus.jpg',
  '2k_neptune.jpg',
  '2k_moon.jpg',
];

const TEXTURES_DIR = 'static/textures';

async function fetchTextures(): Promise<number> {
  await mkdir(TEXTURES_DIR, { recursive: true });
  let downloaded = 0;
  for (const filename of TEXTURES) {
    console.log(`  ${filename}…`);
    const url = `${TEXTURE_BASE_URL}/${filename}`;
    const localPath = join(TEXTURES_DIR, filename);
    await downloadFile(url, localPath);
    downloaded++;
  }
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// AGENCY LOGOS — v0.1.x patch
//
// Source: Wikimedia Commons. All listed logos are public domain (NASA,
// ESA, JAXA, ISRO, ROSCOSMOS, CNSA — government symbols / agency
// emblems) or PD-trivial (SpaceX wordmark). License compliance per
// ADR-016: no third-party runtime dependencies; logos fetched at build
// and committed.
//
// If Wikimedia changes a file path, the fetch will fail gracefully —
// this script logs a warning and continues. The UI falls back to a
// text-only agency badge when an image is missing.
// ──────────────────────────────────────────────────────────────────────

interface AgencyLogo {
  id: string;
  /**
   * Wikimedia Commons filename (case-sensitive, must include extension).
   * Resolved via Special:FilePath which is stable across hash-bucket
   * moves — direct upload.wikimedia.org URLs change when files are
   * recategorised.
   */
  filename: string;
  ext: 'svg' | 'png';
  license: string;
}

const AGENCY_LOGOS: AgencyLogo[] = [
  {
    id: 'nasa',
    filename: 'NASA_logo.svg',
    ext: 'svg',
    license: 'Public domain (US Government work)',
  },
  {
    id: 'esa',
    filename: 'ESA_logo_simple.svg',
    ext: 'svg',
    license: 'Permissive — ESA agency emblem',
  },
  {
    id: 'roscosmos',
    filename: 'Roscosmos_logo_en.svg',
    ext: 'svg',
    license: 'Public domain (Russian Federal Space Agency)',
  },
  {
    id: 'cnsa',
    filename: 'Insignia_of_CNSA.svg',
    ext: 'svg',
    license: 'Public domain (PRC government)',
  },
  {
    id: 'isro',
    filename: 'Indian_Space_Research_Organisation_Logo.svg',
    ext: 'svg',
    license: 'Public domain (Government of India)',
  },
  {
    id: 'jaxa',
    filename: 'Jaxa_logo.svg',
    ext: 'svg',
    license: 'Public domain (Japanese government agency)',
  },
  {
    id: 'spacex',
    filename: 'SpaceX-Logo.svg',
    ext: 'svg',
    license: 'PD-trivial (simple wordmark)',
  },
  {
    id: 'uaesa',
    filename: 'UAE_Space_Agency_logo.svg',
    ext: 'svg',
    license: 'Permissive — UAE agency emblem',
  },
];

const WIKIMEDIA_FILEPATH_BASE = 'https://commons.wikimedia.org/wiki/Special:FilePath';

const LOGOS_DIR = 'static/logos';

// Wikimedia requires a descriptive User-Agent (not a generic
// HTTP-client UA) and rate-limits anonymous bulk downloads. The
// guidance is roughly one request per second for scripts.
const WIKIMEDIA_UA =
  'OrreryBuildBot/0.1 (https://github.com/chipi/orrery; contact: marko.dragoljevic@gmail.com)';
const WIKIMEDIA_DELAY_MS = 1100;

async function downloadFromWikimedia(url: string, dest: string): Promise<void> {
  const res = await fetch(url, { headers: { 'User-Agent': WIKIMEDIA_UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buffer);
}

async function fetchAgencyLogos(): Promise<number> {
  await mkdir(LOGOS_DIR, { recursive: true });
  let downloaded = 0;
  for (let i = 0; i < AGENCY_LOGOS.length; i++) {
    const logo = AGENCY_LOGOS[i];
    const localPath = join(LOGOS_DIR, `${logo.id}.${logo.ext}`);
    const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(logo.filename)}`;
    console.log(`  ${logo.id}.${logo.ext}…`);
    try {
      await downloadFromWikimedia(url, localPath);
      downloaded++;
    } catch (err) {
      // Don't break the build for a missing logo. Wikimedia URLs
      // occasionally rename files; log and continue. The UI degrades
      // gracefully to text-only badges.
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`    ⚠ skipped ${logo.id}: ${msg}`);
    }
    // Throttle to stay under Wikimedia's anonymous-script rate limit.
    if (i < AGENCY_LOGOS.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
    }
  }
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// ROCKET IMAGERY — v0.1.x patch
//
// Source: Wikimedia Commons. Each entry references a Commons file; we
// fetch via Special:FilePath?width=800 so Wikimedia serves a
// downscaled JPEG (~150-300 KB each) regardless of the original
// source size. This sidesteps the per-file 5 MB build budget while
// still giving us a /plan-vehicle-preview-sized image (~280×160px
// rendered).
//
// License compliance per ADR-016: every entry is PD or CC-BY/-SA;
// attribution lines surface on the rocket-detail panel.
//
// Coverage gap: Ariane 6's maiden flight (July 2024) hasn't yet
// produced a CC-licensed landscape launch photo on Commons. The UI
// degrades to text-only when an image is missing.
// ──────────────────────────────────────────────────────────────────────

interface RocketImage {
  id: string;
  filename: string;
  license: string;
}

const ROCKET_IMAGES: RocketImage[] = [
  {
    id: 'falcon-heavy',
    filename: 'SpaceX_Falcon_Heavy_on_the_Launch_Pad.jpg',
    license: 'CC BY-SA 4.0 — SpaceX',
  },
  {
    id: 'starship',
    filename: 'SpaceX_Starship_ignition_during_IFT-5.jpg',
    license: 'CC BY 2.0 — Official SpaceX Photos',
  },
  {
    id: 'sls-block-1',
    filename: 'Launch_of_Artemis_1_(KSC_20221115_Artemis_I_Launch-2).jpg',
    license: 'Public domain (NASA)',
  },
  {
    id: 'atlas-v-541',
    filename: 'Mars_2020_Perseverance_Launch_(NHQ202007300024).jpg',
    license: 'Public domain (NASA)',
  },
  {
    id: 'long-march-5',
    filename: 'Long_March_5_rolling_out_at_WSLS.jpg',
    license: 'CC BY 4.0 — China News Service',
  },
];

const ROCKETS_DIR = 'static/images/rockets';
const ROCKET_THUMB_WIDTH = 800;

async function fetchRocketImages(): Promise<number> {
  await mkdir(ROCKETS_DIR, { recursive: true });
  let downloaded = 0;
  for (let i = 0; i < ROCKET_IMAGES.length; i++) {
    const img = ROCKET_IMAGES[i];
    const localPath = join(ROCKETS_DIR, `${img.id}.jpg`);
    // Wikimedia thumbnail-on-demand: ?width=N gives a downscaled JPEG
    // regardless of the original file's size.
    const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(
      img.filename,
    )}?width=${ROCKET_THUMB_WIDTH}`;
    console.log(`  ${img.id}.jpg…`);
    try {
      await downloadFromWikimedia(url, localPath);
      downloaded++;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`    ⚠ skipped ${img.id}: ${msg}`);
    }
    if (i < ROCKET_IMAGES.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
    }
  }
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// MISSION IMAGERY — NASA Images API + per-mission gallery (v0.1.8)
//
// Source: NASA Images API (https://images-api.nasa.gov). All NASA-
// originated content is public domain; third-party material that
// occasionally appears in their library is identified per-item and
// skipped (we filter by `nasa` in the credit field).
//
// v0.1.8 expansion: instead of one cover photo per mission, we fetch
// up to MISSION_GALLERY_MAX (5) photos per mission and save them as
// `static/images/missions/{id}/01.jpg`, `02.jpg`, ... A manifest
// JSON at `static/data/mission-galleries.json` lists the count per
// mission so the UI knows how many to render.
//
// The first photo (`01.jpg`) is also used as the card cover (the
// existing `static/images/missions/{id}.jpg` files become a single
// alias to `{id}/01.jpg`).
//
// Rate limits: NASA API is generous for anonymous use (~100 req/h).
// We throttle to 600ms between requests as a courtesy.
// ──────────────────────────────────────────────────────────────────────

interface MissionImageQuery {
  id: string;
  query: string;
}

const MISSION_IMAGE_QUERIES: MissionImageQuery[] = [
  // Mars
  { id: 'apollo11', query: 'apollo 11 lunar surface' },
  { id: 'apollo17', query: 'apollo 17 lunar rover' },
  { id: 'artemis3', query: 'artemis program lunar' },
  { id: 'curiosity', query: 'curiosity rover mars' },
  { id: 'hope-probe', query: 'emirates mars mission' },
  { id: 'insight', query: 'insight mars lander' },
  { id: 'mariner4', query: 'mariner 4 mars' },
  { id: 'mars-express', query: 'mars express orbiter' },
  { id: 'mars-pathfinder', query: 'mars pathfinder sojourner' },
  { id: 'mars3', query: 'mars 3 soviet lander' },
  { id: 'maven', query: 'maven mars orbiter' },
  { id: 'mmx', query: 'mars moons exploration phobos' },
  { id: 'perseverance', query: 'perseverance rover mars' },
  { id: 'starship-demo', query: 'starship spacex' },
  { id: 'tianwen1', query: 'tianwen-1 mars china' },
  { id: 'viking1', query: 'viking 1 mars lander' },
  { id: 'mangalyaan', query: 'mangalyaan mars orbiter mission' },
  // Moon
  { id: 'chandrayaan1', query: 'chandrayaan-1 lunar orbiter' },
  { id: 'chandrayaan3', query: 'chandrayaan-3 lunar lander' },
  { id: 'change4', query: 'chang-e 4 farside moon' },
  { id: 'change5', query: 'chang-e 5 lunar sample' },
  { id: 'change6', query: 'chang-e 6 moon' },
  { id: 'clementine', query: 'clementine lunar mission' },
  { id: 'lro', query: 'lunar reconnaissance orbiter' },
  { id: 'luna17', query: 'luna 17 lunokhod' },
  { id: 'luna24', query: 'luna 24 sample return' },
  { id: 'luna9', query: 'luna 9 first soft landing moon' },
  { id: 'slim', query: 'slim lunar lander jaxa' },
];

const MISSIONS_DIR = 'static/images/missions';
const MISSION_GALLERIES_MANIFEST = 'static/data/mission-galleries.json';
const NASA_API_BASE = 'https://images-api.nasa.gov';
const NASA_API_DELAY_MS = 600;
const MISSION_GALLERY_MAX = 5;

interface NasaApiItem {
  data: { title?: string; secondary_creator?: string }[];
  links: { href: string; rel?: string; render?: string }[];
}
interface NasaApiResponse {
  collection: { items: NasaApiItem[] };
}

/** Walk NASA Images API results, picking up to `max` distinct
 *  preview links that look NASA-originated. Returns the URL list. */
async function fetchNasaGalleryUrls(query: string, max: number): Promise<string[]> {
  const searchUrl = `${NASA_API_BASE}/search?q=${encodeURIComponent(query)}&media_type=image`;
  const res = await fetch(searchUrl);
  if (!res.ok) throw new Error(`Search HTTP ${res.status}`);
  const json = (await res.json()) as NasaApiResponse;
  const items = json.collection?.items ?? [];
  if (items.length === 0) throw new Error('No results');
  const urls: string[] = [];
  const seen = new Set<string>();
  // Walk up to 25 items; collect distinct NASA-credited preview links.
  for (const item of items.slice(0, 25)) {
    if (urls.length >= max) break;
    const meta = item.data?.[0];
    const credit = (meta?.secondary_creator ?? '').toLowerCase();
    const isOk =
      !credit ||
      credit.includes('nasa') ||
      credit.includes('jpl') ||
      credit.includes('gsfc') ||
      credit.includes('apl') ||
      credit.includes('msss') ||
      credit.includes('asu');
    if (!isOk) continue;
    const previewLink =
      item.links.find((l) => l.render === 'image' || l.rel === 'preview')?.href ??
      item.links[0]?.href;
    if (!previewLink || seen.has(previewLink)) continue;
    seen.add(previewLink);
    urls.push(previewLink);
  }
  if (urls.length === 0) throw new Error('No NASA-licensed images in results');
  return urls;
}

// Wikimedia fallback for missions not in NASA's library (mostly
// non-NASA: CNSA, JAXA, ROSCOSMOS, ISRO, MBRSC). Curated filenames
// verified to exist on Commons; CC-BY/-SA or PD licensed.
const WIKIMEDIA_MISSION_FALLBACK: Record<string, string> = {
  change5: "Chang'e_5_as_seen_by_LRO_02.png",
  change4: 'ChangE-4_-_PCAM.png',
  change6: "Chang'e_6_mockup_at_IAC_2024_02.jpg",
  slim: 'M1460739214L_JAXA_SLIM_landing_site_imaged_by_Lunar_Reconnaissance_Orbiter_Camera_(LROC).png',
  'hope-probe': 'نجاح_وصول_مسبار_الأمل_لمدار_المريخ.jpg',
  mangalyaan: 'Mars_Orbiter_Mission_-_India_-_ArtistsConcept.jpg',
  tianwen1: 'Orbital_trajectory_of_Tianwen-1_around_Mars.png',
  chandrayaan3: 'Chandrayaan_3_Vikram_lander_stereo_(53167467822)_crop.png',
  chandrayaan1: 'Chandrayaan-1-01.jpg',
  luna9: 'Luna_9_Space_Probe_1.jpg',
  luna24: 'Moon_map_of_sample_return_sites.png',
};

async function fetchMissionImages(): Promise<number> {
  await mkdir(MISSIONS_DIR, { recursive: true });
  await mkdir('static/data', { recursive: true });

  /** Manifest: { missionId: count } so the UI knows how many photos
   *  it has and renders thumbnails 01..N. Empty entries mean no
   *  gallery (UI degrades to text-only). */
  const manifest: Record<string, number> = {};
  let totalPhotos = 0;

  for (let i = 0; i < MISSION_IMAGE_QUERIES.length; i++) {
    const m = MISSION_IMAGE_QUERIES[i];
    const missionDir = join(MISSIONS_DIR, m.id);
    await mkdir(missionDir, { recursive: true });
    process.stdout.write(`  ${m.id}…`);

    let urls: string[] = [];
    try {
      urls = await fetchNasaGalleryUrls(m.query, MISSION_GALLERY_MAX);
    } catch {
      // NASA API returned nothing usable. Fall through to Wikimedia
      // fallback if curated; that's a single-image gallery.
      const fallback = WIKIMEDIA_MISSION_FALLBACK[m.id];
      if (fallback) {
        try {
          const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(fallback)}?width=800`;
          await downloadFromWikimedia(url, join(missionDir, '01.jpg'));
          // Mirror as the legacy cover at static/images/missions/{id}.jpg
          // so existing /missions card paths keep working.
          await downloadFromWikimedia(url, join(MISSIONS_DIR, `${m.id}.jpg`));
          manifest[m.id] = 1;
          totalPhotos++;
          process.stdout.write(' wikimedia (1)\n');
          continue;
        } catch (err2) {
          const msg = err2 instanceof Error ? err2.message : String(err2);
          process.stdout.write(` ⚠ skipped (nasa+wikimedia: ${msg})\n`);
          manifest[m.id] = 0;
          continue;
        }
      } else {
        process.stdout.write(' ⚠ skipped (no api results, no fallback)\n');
        manifest[m.id] = 0;
        continue;
      }
    }

    // Download each URL → 01.jpg, 02.jpg, ...
    let saved = 0;
    for (let n = 0; n < urls.length; n++) {
      const filename = `${String(n + 1).padStart(2, '0')}.jpg`;
      try {
        const imgRes = await fetch(urls[n]);
        if (!imgRes.ok) continue;
        const buffer = Buffer.from(await imgRes.arrayBuffer());
        await writeFile(join(missionDir, filename), buffer);
        // Mirror the first image as the legacy cover at
        // static/images/missions/{id}.jpg for /missions card.
        if (n === 0) {
          await writeFile(join(MISSIONS_DIR, `${m.id}.jpg`), buffer);
        }
        saved++;
      } catch {
        // Single-image fail; continue with the rest.
      }
    }
    manifest[m.id] = saved;
    totalPhotos += saved;
    process.stdout.write(` ${saved}\n`);

    if (i < MISSION_IMAGE_QUERIES.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, NASA_API_DELAY_MS));
    }
  }

  // Write the manifest (sorted keys → byte-identical re-runs).
  const sortedManifest: Record<string, number> = {};
  for (const k of Object.keys(manifest).sort()) sortedManifest[k] = manifest[k];
  await writeFile(MISSION_GALLERIES_MANIFEST, JSON.stringify(sortedManifest, null, 2) + '\n');
  console.log(
    `  → manifest written to ${MISSION_GALLERIES_MANIFEST} (${totalPhotos} photos total)`,
  );

  return totalPhotos;
}

// ──────────────────────────────────────────────────────────────────────
// SHARED HELPERS
// ──────────────────────────────────────────────────────────────────────

async function downloadFile(url: string, dest: string): Promise<void> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: HTTP ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buffer);
}

// ──────────────────────────────────────────────────────────────────────
// MAIN
// ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('Fetching fonts:');
  const fontCount = await fetchFonts();
  console.log(`  → ${fontCount} woff2 files; wrote ${FONTS_CSS_OUT}\n`);

  console.log('Fetching textures:');
  const textureCount = await fetchTextures();
  console.log(`  → ${textureCount} texture files in ${TEXTURES_DIR}\n`);

  console.log('Fetching agency logos:');
  const logoCount = await fetchAgencyLogos();
  console.log(`  → ${logoCount} logo files in ${LOGOS_DIR}\n`);

  console.log('Fetching rocket imagery:');
  const rocketCount = await fetchRocketImages();
  console.log(`  → ${rocketCount} rocket files in ${ROCKETS_DIR}\n`);

  console.log('Fetching mission imagery (NASA Images API):');
  const missionCount = await fetchMissionImages();
  console.log(`  → ${missionCount} mission files in ${MISSIONS_DIR}\n`);

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
