/**
 * Fetches external assets at build time per ADR-016.
 *
 * Slice 1: Google Fonts (Bebas Neue, Space Mono, Crimson Pro).
 * Slice 3: planet textures + moon texture from Solar System Scope.
 * v0.1.x patches: agency logos from Wikimedia Commons.
 * Future: NASA Images API for per-mission imagery; rocket reference imagery.
 *
 * Run via: npm run fetch-assets
 *
 * Targeted mission imagery only (merges into mission-galleries.json):
 *   npm run fetch-assets -- --missions-only=galileo,voyager-2
 *
 * ISS module galleries only (merges into iss-galleries.json):
 *   npm run fetch-assets -- --iss-only
 *   npm run fetch-assets -- --iss-only=cupola,zarya
 */

import { writeFile, mkdir, readdir, readFile, copyFile } from 'node:fs/promises';
import type { Destination } from '../src/types/mission.js';
import { join, dirname } from 'node:path';
import { createCanvas } from 'canvas';
import { earthPos, outboundArc } from '../src/lib/mission-arc.js';
import { DESTINATIONS, R_EARTH_AU, type DestinationId } from '../src/lib/lambert-grid.constants.js';
import { missionDestToHeliocentricDestinationId } from '../src/lib/mission-dest.js';
import { dateToSimDay } from '../src/lib/sim-day.js';

// ──────────────────────────────────────────────────────────────────────
// FONTS — Slice 1
// ──────────────────────────────────────────────────────────────────────

interface FontDef {
  family: string;
  cssParam: string;
}

const FONTS: FontDef[] = [
  { family: 'Bebas Neue', cssParam: 'Bebas+Neue' },
  { family: 'Space Mono', cssParam: 'Space+Mono:wght@400;700' },
  { family: 'Crimson Pro', cssParam: 'Crimson+Pro:ital,wght@0,400;0,600;1,400' },
];

const FONT_BASE_URL = 'https://fonts.googleapis.com/css2';
// User-Agent that triggers woff2 responses from Google Fonts.
const FONT_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FONTS_DIR = 'static/fonts';
const FONTS_CSS_OUT = 'src/lib/styles/fonts.css';

async function fetchFontCss(font: FontDef): Promise<string> {
  const url = `${FONT_BASE_URL}?family=${font.cssParam}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': FONT_UA } });
  if (!res.ok) throw new Error(`Failed to fetch CSS for ${font.family}: HTTP ${res.status}`);
  return res.text();
}

function extractWoff2Urls(css: string): Set<string> {
  const urls = new Set<string>();
  const regex = /url\((https:\/\/[^)]+\.woff2)\)/g;
  let match;
  while ((match = regex.exec(css)) !== null) {
    urls.add(match[1]);
  }
  return urls;
}

async function fetchFonts(): Promise<number> {
  await mkdir(FONTS_DIR, { recursive: true });
  await mkdir(dirname(FONTS_CSS_OUT), { recursive: true });

  let combinedCss =
    '/* Auto-generated by scripts/fetch-assets.ts. Do not edit by hand.\n' +
    '   Re-run with: npm run fetch-assets */\n\n';
  let downloaded = 0;

  for (const font of FONTS) {
    console.log(`  ${font.family}…`);
    const css = await fetchFontCss(font);
    const urls = extractWoff2Urls(css);

    let localCss = css;
    for (const url of urls) {
      const filename = url.split('/').pop();
      if (!filename) throw new Error(`Could not derive filename from ${url}`);
      const localPath = join(FONTS_DIR, filename);
      await downloadFile(url, localPath);
      localCss = localCss.replaceAll(url, `/fonts/${filename}`);
      downloaded++;
    }

    combinedCss += `/* ${font.family} */\n${localCss}\n`;
  }

  await writeFile(FONTS_CSS_OUT, combinedCss);
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// PLANET + MOON TEXTURES — Slice 3
//
// Source: Solar System Scope (https://www.solarsystemscope.com/textures/)
// Licence: CC BY 4.0. Attribution: "Solar System Scope" in mission-credits page.
// 2K resolution chosen as a balance of detail and bundle size (~3 MB total).
// Issue #3 originally pointed at three.js's r128 examples/textures/planets/
// folder, which doesn't actually contain 2k_*.jpg files in r128 — only Earth
// and Moon textures. SSS is the canonical source for the full set.
// ──────────────────────────────────────────────────────────────────────

const TEXTURE_BASE_URL = 'https://www.solarsystemscope.com/textures/download';

const TEXTURES = [
  '2k_sun.jpg',
  '2k_mercury.jpg',
  '2k_venus_atmosphere.jpg',
  '2k_earth_daymap.jpg',
  '2k_mars.jpg',
  '2k_jupiter.jpg',
  '2k_saturn.jpg',
  '2k_uranus.jpg',
  '2k_neptune.jpg',
  '2k_moon.jpg',
];

const TEXTURES_DIR = 'static/textures';

async function fetchTextures(): Promise<number> {
  await mkdir(TEXTURES_DIR, { recursive: true });
  let downloaded = 0;
  for (const filename of TEXTURES) {
    console.log(`  ${filename}…`);
    const url = `${TEXTURE_BASE_URL}/${filename}`;
    const localPath = join(TEXTURES_DIR, filename);
    await downloadFile(url, localPath);
    downloaded++;
  }
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// AGENCY LOGOS — v0.1.x patch
//
// Source: Wikimedia Commons. All listed logos are public domain (NASA,
// ESA, JAXA, ISRO, ROSCOSMOS, CNSA — government symbols / agency
// emblems) or PD-trivial (SpaceX wordmark). License compliance per
// ADR-016: no third-party runtime dependencies; logos fetched at build
// and committed.
//
// If Wikimedia changes a file path, the fetch will fail gracefully —
// this script logs a warning and continues. The UI falls back to a
// text-only agency badge when an image is missing.
// ──────────────────────────────────────────────────────────────────────

interface AgencyLogo {
  id: string;
  /**
   * Wikimedia Commons filename (case-sensitive, must include extension).
   * Resolved via Special:FilePath which is stable across hash-bucket
   * moves — direct upload.wikimedia.org URLs change when files are
   * recategorised.
   */
  filename: string;
  ext: 'svg' | 'png';
  license: string;
}

const AGENCY_LOGOS: AgencyLogo[] = [
  {
    id: 'nasa',
    filename: 'NASA_logo.svg',
    ext: 'svg',
    license: 'Public domain (US Government work)',
  },
  {
    id: 'esa',
    filename: 'ESA_logo_simple.svg',
    ext: 'svg',
    license: 'Permissive — ESA agency emblem',
  },
  {
    id: 'roscosmos',
    filename: 'Roscosmos_logo_en.svg',
    ext: 'svg',
    license: 'Public domain (Russian Federal Space Agency)',
  },
  {
    id: 'cnsa',
    filename: 'Insignia_of_CNSA.svg',
    ext: 'svg',
    license: 'Public domain (PRC government)',
  },
  {
    id: 'isro',
    filename: 'Indian_Space_Research_Organisation_Logo.svg',
    ext: 'svg',
    license: 'Public domain (Government of India)',
  },
  {
    id: 'jaxa',
    filename: 'Jaxa_logo.svg',
    ext: 'svg',
    license: 'Public domain (Japanese government agency)',
  },
  {
    id: 'spacex',
    filename: 'SpaceX-Logo.svg',
    ext: 'svg',
    license: 'PD-trivial (simple wordmark)',
  },
  {
    id: 'uaesa',
    filename: 'UAE_Space_Agency_logo.svg',
    ext: 'svg',
    license: 'Permissive — UAE agency emblem',
  },
];

const WIKIMEDIA_FILEPATH_BASE = 'https://commons.wikimedia.org/wiki/Special:FilePath';

const LOGOS_DIR = 'static/logos';

// Wikimedia requires a descriptive User-Agent (not a generic
// HTTP-client UA) and rate-limits anonymous bulk downloads. The
// guidance is roughly one request per second for scripts.
const WIKIMEDIA_UA =
  'OrreryBuildBot/0.1 (https://github.com/chipi/orrery; contact: marko.dragoljevic@gmail.com)';
const WIKIMEDIA_DELAY_MS = 1100;

async function downloadFromWikimedia(url: string, dest: string): Promise<void> {
  const res = await fetch(url, { headers: { 'User-Agent': WIKIMEDIA_UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buffer);
}

// ──────────────────────────────────────────────────────────────────────
// PLANET DISC PHOTOS — v0.1.8 + v0.1.9
//
// Square disc shots used as 2D-mode disc backgrounds on /moon
// (replacing the previous grey gradient) and /earth (replacing the
// blue radial gradient). Fetched via Wikimedia Special:FilePath?width=800
// to keep file sizes manageable.
// ──────────────────────────────────────────────────────────────────────

const LUNAR_DISC_PHOTOS: { id: string; filename: string; license: string }[] = [
  {
    id: 'moon_near',
    filename: 'Full_Moon_Luc_Viatour.jpg',
    license: 'CC BY-SA 3.0 — Luc Viatour',
  },
  {
    id: 'moon_far',
    filename: 'Moon_Farside_LRO.jpg',
    license: 'Public domain (NASA LRO)',
  },
  {
    id: 'earth_disc',
    filename: 'The_Blue_Marble,_AS17-148-22727.jpg',
    license: 'Public domain (NASA Apollo 17 — AS17-148-22727)',
  },
];

async function fetchLunarDiscPhotos(): Promise<number> {
  await mkdir(TEXTURES_DIR, { recursive: true });
  let downloaded = 0;
  for (let i = 0; i < LUNAR_DISC_PHOTOS.length; i++) {
    const photo = LUNAR_DISC_PHOTOS[i];
    const localPath = join(TEXTURES_DIR, `${photo.id}.jpg`);
    const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(photo.filename)}?width=800`;
    console.log(`  ${photo.id}.jpg…`);
    try {
      await downloadFromWikimedia(url, localPath);
      downloaded++;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`    ⚠ skipped ${photo.id}: ${msg}`);
    }
    if (i < LUNAR_DISC_PHOTOS.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
    }
  }
  return downloaded;
}

async function fetchAgencyLogos(): Promise<number> {
  await mkdir(LOGOS_DIR, { recursive: true });
  let downloaded = 0;
  for (let i = 0; i < AGENCY_LOGOS.length; i++) {
    const logo = AGENCY_LOGOS[i];
    const localPath = join(LOGOS_DIR, `${logo.id}.${logo.ext}`);
    const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(logo.filename)}`;
    console.log(`  ${logo.id}.${logo.ext}…`);
    try {
      await downloadFromWikimedia(url, localPath);
      downloaded++;
    } catch (err) {
      // Don't break the build for a missing logo. Wikimedia URLs
      // occasionally rename files; log and continue. The UI degrades
      // gracefully to text-only badges.
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`    ⚠ skipped ${logo.id}: ${msg}`);
    }
    // Throttle to stay under Wikimedia's anonymous-script rate limit.
    if (i < AGENCY_LOGOS.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
    }
  }
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// ROCKET IMAGERY — v0.1.x patch
//
// Source: Wikimedia Commons. Each entry references a Commons file; we
// fetch via Special:FilePath?width=800 so Wikimedia serves a
// downscaled JPEG (~150-300 KB each) regardless of the original
// source size. This sidesteps the per-file 5 MB build budget while
// still giving us a /plan-vehicle-preview-sized image (~280×160px
// rendered).
//
// License compliance per ADR-016: every entry is PD or CC-BY/-SA;
// attribution lines surface on the rocket-detail panel.
//
// Coverage gap: Ariane 6's maiden flight (July 2024) hasn't yet
// produced a CC-licensed landscape launch photo on Commons. The UI
// degrades to text-only when an image is missing.
// ──────────────────────────────────────────────────────────────────────

interface RocketImage {
  id: string;
  filename: string;
  license: string;
}

const ROCKET_IMAGES: RocketImage[] = [
  {
    id: 'falcon-heavy',
    filename: 'SpaceX_Falcon_Heavy_on_the_Launch_Pad.jpg',
    license: 'CC BY-SA 4.0 — SpaceX',
  },
  {
    id: 'starship',
    filename: 'SpaceX_Starship_ignition_during_IFT-5.jpg',
    license: 'CC BY 2.0 — Official SpaceX Photos',
  },
  {
    id: 'sls-block-1',
    filename: 'Launch_of_Artemis_1_(KSC_20221115_Artemis_I_Launch-2).jpg',
    license: 'Public domain (NASA)',
  },
  {
    id: 'atlas-v-541',
    filename: 'Mars_2020_Perseverance_Launch_(NHQ202007300024).jpg',
    license: 'Public domain (NASA)',
  },
  {
    id: 'long-march-5',
    filename: 'Long_March_5_rolling_out_at_WSLS.jpg',
    license: 'CC BY 4.0 — China News Service',
  },
  {
    id: 'ariane-6',
    filename: 'Ariane_6_on_pad.jpg',
    license: 'CC BY-SA — ESA / Wikimedia',
  },
  {
    id: 'lvm3',
    filename:
      'LVM3_M4,_Chandrayaan-3_-_Launch_vehicle_lifting_off_from_the_Second_Launch_Pad_(SLP)_of_SDSC-SHAR,_Sriharikota_(edit).jpg',
    license: 'Government Open Data License — India / ISRO',
  },
  {
    id: 'pslv-xl',
    filename: 'PSLV-C11_launch2.jpg',
    license: 'Government Open Data License — India / ISRO',
  },
  {
    id: 'h3',
    filename: '2024.11.04 H3ロケット4号機きらめき３号打上げ.jpg',
    license: 'CC BY 4.0 — JAXA',
  },
  {
    id: 'h-iia',
    filename: 'H-IIA_F12_launching_IGS-R2.jpg',
    license: 'CC BY 4.0 — JAXA',
  },
  {
    id: 'long-march-3b',
    filename: 'The_Launch_of_Long_March_3B_Rocket.jpg',
    license: 'CC BY 4.0 — China',
  },
  {
    id: 'soyuz-fregat',
    filename: 'Soyuz_TMA-5_launch.jpg',
    license: 'Public domain (NASA)',
  },
  {
    id: 'proton-m',
    filename: 'Proton-K-Zarya.jpg',
    license: 'Public domain (NASA)',
  },
];

const ROCKETS_DIR = 'static/images/rockets';
const ROCKET_THUMB_WIDTH = 800;

async function fetchRocketImages(): Promise<number> {
  await mkdir(ROCKETS_DIR, { recursive: true });
  let downloaded = 0;
  for (let i = 0; i < ROCKET_IMAGES.length; i++) {
    const img = ROCKET_IMAGES[i];
    const localPath = join(ROCKETS_DIR, `${img.id}.jpg`);
    // Wikimedia thumbnail-on-demand: ?width=N gives a downscaled JPEG
    // regardless of the original file's size.
    const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(
      img.filename,
    )}?width=${ROCKET_THUMB_WIDTH}`;
    console.log(`  ${img.id}.jpg…`);
    try {
      await downloadFromWikimedia(url, localPath);
      downloaded++;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`    ⚠ skipped ${img.id}: ${msg}`);
    }
    if (i < ROCKET_IMAGES.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
    }
  }
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// MISSION IMAGERY — NASA Images API + per-mission gallery (v0.1.8)
//
// Source: NASA Images API (https://images-api.nasa.gov). All NASA-
// originated content is public domain; third-party material that
// occasionally appears in their library is identified per-item and
// skipped (we filter by `nasa` in the credit field).
//
// v0.1.8 expansion: instead of one cover photo per mission, we fetch
// up to MISSION_GALLERY_MAX (5) photos per mission and save them as
// `static/images/missions/{id}/01.jpg`, `02.jpg`, ... A manifest
// JSON at `static/data/mission-galleries.json` lists the count per
// mission so the UI knows how many to render.
//
// The first photo (`01.jpg`) is also used as the card cover (the
// existing `static/images/missions/{id}.jpg` files become a single
// alias to `{id}/01.jpg`).
//
// Rate limits: NASA API is generous for anonymous use (~100 req/h).
// We throttle to 600ms between requests as a courtesy.
// ──────────────────────────────────────────────────────────────────────

interface MissionImageQuery {
  id: string;
  query: string;
}

const MISSION_IMAGE_QUERIES: MissionImageQuery[] = [
  // Mars
  { id: 'apollo11', query: 'apollo 11 lunar surface' },
  { id: 'apollo17', query: 'apollo 17 lunar rover' },
  { id: 'artemis3', query: 'artemis program lunar' },
  { id: 'curiosity', query: 'curiosity rover mars' },
  { id: 'hope-probe', query: 'emirates mars mission' },
  { id: 'insight', query: 'insight mars lander' },
  { id: 'mariner4', query: 'mariner 4 mars' },
  { id: 'mars-express', query: 'mars express orbiter' },
  { id: 'mars-pathfinder', query: 'mars pathfinder sojourner' },
  { id: 'mars3', query: 'mars 3 soviet lander' },
  { id: 'maven', query: 'maven mars orbiter' },
  { id: 'mmx', query: 'mars moons exploration phobos' },
  { id: 'perseverance', query: 'perseverance rover mars' },
  { id: 'starship-demo', query: 'starship spacex' },
  { id: 'starship-mars-crew', query: 'starship mars artist concept' },
  { id: 'inspiration-mars', query: 'mars free return crewed' },
  { id: 'tianwen1', query: 'tianwen-1 mars china' },
  { id: 'viking1', query: 'viking 1 mars lander' },
  { id: 'mangalyaan', query: 'mangalyaan mars orbiter mission' },
  // Moon
  { id: 'chandrayaan1', query: 'chandrayaan-1 lunar orbiter' },
  { id: 'chandrayaan3', query: 'chandrayaan-3 lunar lander' },
  { id: 'change4', query: 'chang-e 4 farside moon' },
  { id: 'change5', query: 'chang-e 5 lunar sample' },
  { id: 'change6', query: 'chang-e 6 moon' },
  { id: 'clementine', query: 'clementine lunar mission' },
  { id: 'lro', query: 'lunar reconnaissance orbiter' },
  { id: 'luna17', query: 'luna 17 lunokhod' },
  { id: 'luna24', query: 'luna 24 sample return' },
  { id: 'luna9', query: 'luna 9 first soft landing moon' },
  { id: 'slim', query: 'slim lunar lander jaxa' },
  { id: 'artemis2', query: 'artemis 2 orion crew' },
  { id: 'blue-moon-mk1', query: 'blue origin blue moon lander' },
  { id: 'galileo', query: 'galileo spacecraft jupiter' },
  { id: 'voyager-2', query: 'voyager 2 neptune flyby' },
  { id: 'new-horizons', query: 'new horizons pluto flyby' },
  { id: 'dawn', query: 'dawn spacecraft ceres' },
];

const MISSIONS_DIR = 'static/images/missions';
const MISSION_GALLERIES_MANIFEST = 'static/data/mission-galleries.json';
const NASA_API_BASE = 'https://images-api.nasa.gov';
const NASA_API_DELAY_MS = 600;
const MISSION_GALLERY_MAX = 5;

interface NasaApiItem {
  data: { title?: string; secondary_creator?: string }[];
  links: { href: string; rel?: string; render?: string }[];
}
interface NasaApiResponse {
  collection: { items: NasaApiItem[] };
}

/** Walk NASA Images API results, picking up to `max` distinct
 *  preview links that look NASA-originated. Returns the URL list. */
async function fetchNasaGalleryUrls(query: string, max: number): Promise<string[]> {
  const searchUrl = `${NASA_API_BASE}/search?q=${encodeURIComponent(query)}&media_type=image`;
  const res = await fetch(searchUrl);
  if (!res.ok) throw new Error(`Search HTTP ${res.status}`);
  const json = (await res.json()) as NasaApiResponse;
  const items = json.collection?.items ?? [];
  if (items.length === 0) throw new Error('No results');
  const urls: string[] = [];
  const seen = new Set<string>();
  // Walk up to 25 items; collect distinct NASA-credited preview links.
  for (const item of items.slice(0, 25)) {
    if (urls.length >= max) break;
    const meta = item.data?.[0];
    const credit = (meta?.secondary_creator ?? '').toLowerCase();
    const isOk =
      !credit ||
      credit.includes('nasa') ||
      credit.includes('jpl') ||
      credit.includes('gsfc') ||
      credit.includes('apl') ||
      credit.includes('msss') ||
      credit.includes('asu');
    if (!isOk) continue;
    const previewLink =
      item.links.find((l) => l.render === 'image' || l.rel === 'preview')?.href ??
      item.links[0]?.href;
    if (!previewLink || seen.has(previewLink)) continue;
    seen.add(previewLink);
    urls.push(previewLink);
  }
  if (urls.length === 0) throw new Error('No NASA-licensed images in results');
  return urls;
}

// Wikimedia fallback for missions not in NASA's library (mostly
// non-NASA: CNSA, JAXA, ROSCOSMOS, ISRO, MBRSC). Curated filenames
// verified to exist on Commons; CC-BY/-SA or PD licensed.
const WIKIMEDIA_MISSION_FALLBACK: Record<string, string> = {
  change5: "Chang'e_5_as_seen_by_LRO_02.png",
  change4: 'ChangE-4_-_PCAM.png',
  change6: "Chang'e_6_mockup_at_IAC_2024_02.jpg",
  slim: 'M1460739214L_JAXA_SLIM_landing_site_imaged_by_Lunar_Reconnaissance_Orbiter_Camera_(LROC).png',
  'hope-probe': 'نجاح_وصول_مسبار_الأمل_لمدار_المريخ.jpg',
  mangalyaan: 'Mars_Orbiter_Mission_-_India_-_ArtistsConcept.jpg',
  tianwen1: 'Orbital_trajectory_of_Tianwen-1_around_Mars.png',
  chandrayaan3: 'Chandrayaan_3_Vikram_lander_stereo_(53167467822)_crop.png',
  chandrayaan1: 'Chandrayaan-1-01.jpg',
  luna9: 'Luna_9_Space_Probe_1.jpg',
  luna24: 'Moon_map_of_sample_return_sites.png',
  'blue-moon-mk1': "Jeff_Bezos_unveils_Blue_Origin's_lunar_lander_'Blue_Moon'_(50416497208).jpg",
  'inspiration-mars': 'Mars_atmosphere_2.jpg',
  'starship-mars-crew': 'Starship_full_stack.jpg',
  artemis2: 'Artemis_2_crew_portrait.jpg',
  /** Outer-planet / small-body catalogue — NASA API often lacks usable credits. */
  galileo: 'Galileo_spacecraft_model.png',
  'voyager-2': 'Voyager_2_spacecraft.jpg',
  'new-horizons': 'New_Horizons_spacecraft_(crop).jpg',
  dawn: 'Dawn_spacecraft_arrival_at_Ceres_(artist_concept).jpg',
};

// Gallery-mode top-up for missions where NASA's library has zero or
// few NASA-credited results — typically every non-NASA mission.
// Each entry is an additional 2–4 Wikimedia Commons filenames that
// fill out the mission's GALLERY tab beyond the single-image cover
// fallback above. Same CC/PD licensing constraint as the cover list.
//
// Files are tried in order; the script stops once the gallery hits
// MISSION_GALLERY_MAX or the list is exhausted. Missions that already
// hit max via NASA results don't trigger this path.
const WIKIMEDIA_MISSION_GALLERY_FALLBACK: Record<string, string[]> = {
  change4: [
    "Chang'e_4_lander.jpg",
    "Chang'e_4_Lander-_A_Closer_Look_(01_m1303619844lr_closC5A1C).jpg",
    'The_first_panorama_from_the_far_side_of_the_moon.jpg',
    "Chang'e_4_Rover_Comes_into_View_(LROC1091_-_content_M1303570617_LRmos_warp_1100p_crop).png",
  ],
  change5: [
    "Chang'e_5_Moon_Sample.png",
    "Chang'e_5-_After_Blast_Off_(LROC1186_-_content_M1367366229LR_mos_str01_1100x1100).png",
    'Chang-e_5_lander_ascender_assembly_test.png',
    "Returner_and_Main_Parachute_of_Chang'e_5.jpg",
  ],
  change6: [
    "Chang'e_6_lunar_samples_at_IAC_2024_01.jpg",
    "First_Look-_Chang'e_6_(LROC1374).jpg",
    "Lunar_soil_sample_collected_by_Chang'e_6_display_on_Expo_2025.jpg",
  ],
  chandrayaan1: [
    'PSLV-C11_launch2.jpg',
    'Chandrayaan1_Spacecraft_Discovery_Moon_Water.jpg',
    'Water_Detected_at_High_Latitudes_on_the_Moon.jpg',
  ],
  chandrayaan3: [
    'Chandrayaan3-landed.jpg',
    'Chandrayaan-3,_LVM3_M4_lifting_off_from_SDSC_SHAR.jpg',
    'Vikram_Simulation.jpg',
    'VIKRAM&PRAGYANMODEL.jpg',
  ],
  mangalyaan: [
    'Mars_Orbiter_Mission.jpg',
    'India_as_seen_by_Mars_Colour_Camera_(MCC)_during_the_Mars_Orbiter_Mission_(MOM)_journey_towards_Mars.png',
    'Mars_Orbiter_Mission_in_cleanroom_(1).jpg',
    'PM_witnesses_the_insertion_of_Mars_Orbiter_Mission_into_Martian_orbit.jpg',
  ],
  slim: [
    'SLIM_half_scale_model.png',
    'SLIM_landing_site.jpg',
    'SLIM-LandingShockAbsorber-TestUsed.jpg',
    'SLIM-LEV1-LEV2-JAXA-SagamiharaCampus-AdvancedFacilityForSpaceExploration-SpaceExplorationField.jpg',
  ],
  'hope-probe': [
    'Emirates_Mars_Mission_mockup_at_IAC_2021_01.jpg',
    'Emirates_Mars_Mission_mockup_at_IAC_2021_02.jpg',
    'المركبة_الفضائية_العربية_الإماراتية_(الأمل).jpg',
  ],
  luna9: ['First_Photo_from_the_Surface_of_the_Moon.jpg'],
  'blue-moon-mk1': [
    'Blue_Moon_Mark_2_Lunar_Lander_(2023).jpg',
    'BE-7_engine_hot_fire.jpg',
    'New_Glenn_first_stage_at_LC-36.jpg',
  ],
  'inspiration-mars': [
    'Mars_Hubble.jpg',
    'Free_return_trajectory.svg',
    'Crewed_Mars_mission_concept.jpg',
  ],
  'starship-mars-crew': [
    'Starship_render_above_Mars.jpg',
    'SpaceX_Mars_base_alpha_concept.jpg',
    'Starship_orbital_refilling.jpg',
  ],
  artemis2: [
    'Artemis_II_mission_patch.png',
    'Orion_spacecraft_after_water_recovery_(NHQ202308300013).jpg',
    'SLS_rocket_ignition.jpg',
    'Earthrise_(Apollo_8).jpg',
  ],
  luna17: [
    'Luna_17_lander.png',
    'M127159138LC_Luna_17_lander.jpg',
    'Lunokhod_1_Revisited_(LROC402_-_M175502049R_L17_thumb).png',
    'LROC_Coordinates_of_Robotic_Spacecraft_-_2013_Update_(LROC650_-_M175502049RE_luna17).png',
  ],
  luna24: [
    'Mare_Crisium-_Failure_then_Success_(LROC461_-_luna23_24_regional).png',
    'Soviet_Union_Lunar_Sample_Return_Missions_(LROCM119449091RE_L24_ano).png',
    'Luna24_rev_fig.png',
  ],
  mars3: [
    'Mars_3_surface_transmission.jpg',
    '1972._Марс-3.jpg',
    'PIA16920-MarsSoviet3Lander1971-PossibleDebrisField.jpg',
    'Possible_Mars_3_lander_from_MRO_ESP_031036_1345_MRGB.abrowse.jpg',
  ],
  clementine: [
    'Clementine_lunar.jpg',
    "Clementine_Fully_Deployed_(Artist's_Concept)_(PIA18159).jpg",
    'Clementine_final_checks.jpg',
    'Appleton_cráter_(Clementine).jpg',
  ],
  galileo: [
    'Jupiter_from_Galileo_Prime_Meridian.jpg',
    'Io_volcanism_from_Galileo.jpg',
    'Artists_concept_of_Galileo_spacecraft.jpg',
  ],
  'voyager-2': [
    'Neptune_Full_Disk_View_(7564918848).jpg',
    'Triton_moon_mosaic_Voyager_2_(large).jpg',
    'Voyager_spacecraft.jpg',
  ],
  'new-horizons': [
    'Pluto-Color-NewHorizons-20150713.jpg',
    '486958_Arrokoth_(crop_of_binary)_color_(cropped).jpg',
    'NewHorizons_39_july14_2015.jpg',
  ],
  dawn: [
    'Ceres_-_RC3_-_Haulani_Crater_-_21778369873.jpg',
    'Vesta_in_natural_color.jpg',
    'Dawn-spacecraft.jpg',
  ],
};

/** Top up a mission's gallery from WIKIMEDIA_MISSION_GALLERY_FALLBACK
 *  starting at slot `nextIndex` (1-based). Returns the new total
 *  count of saved images. Skips silently if a single file errors so
 *  one bad URL doesn't tank the whole top-up. */
async function topUpWikimediaGallery(
  missionId: string,
  missionDir: string,
  nextIndex: number,
  legacyCoverPath: string,
  hasLegacyCover: boolean,
): Promise<number> {
  const list = WIKIMEDIA_MISSION_GALLERY_FALLBACK[missionId];
  if (!list || list.length === 0) return nextIndex - 1;
  let saved = nextIndex - 1;
  for (const filename of list) {
    if (saved >= MISSION_GALLERY_MAX) break;
    const slot = `${String(saved + 1).padStart(2, '0')}.jpg`;
    const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(filename)}?width=800`;
    try {
      await downloadFromWikimedia(url, join(missionDir, slot));
      // If this is the very first image saved (no NASA + no cover
      // fallback), also write the legacy cover so /missions cards
      // don't 404.
      if (saved === 0 && !hasLegacyCover) {
        await downloadFromWikimedia(url, legacyCoverPath);
      }
      saved++;
      // Politeness — Commons guidance is ~1 req/sec.
      await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
    } catch {
      // Skip this entry; try the next.
    }
  }
  return saved;
}

async function fetchMissionImages(onlyIds?: string[]): Promise<number> {
  await mkdir(MISSIONS_DIR, { recursive: true });
  await mkdir('static/data', { recursive: true });

  /** Manifest: { missionId: count } so the UI knows how many photos
   *  it has and renders thumbnails 01..N. Empty entries mean no
   *  gallery (UI degrades to text-only). */
  let prevManifest: Record<string, number> = {};
  if (onlyIds?.length) {
    try {
      prevManifest = JSON.parse(await readFile(MISSION_GALLERIES_MANIFEST, 'utf8')) as Record<
        string,
        number
      >;
    } catch {
      /* no existing manifest */
    }
  }
  const manifest: Record<string, number> = onlyIds?.length ? { ...prevManifest } : {};
  let totalPhotos = 0;

  const queries = onlyIds?.length
    ? MISSION_IMAGE_QUERIES.filter((q) => onlyIds.includes(q.id))
    : MISSION_IMAGE_QUERIES;

  if (onlyIds?.length && queries.length === 0) {
    console.warn('  ⚠ --missions-only: no ids matched MISSION_IMAGE_QUERIES');
    return 0;
  }

  for (let i = 0; i < queries.length; i++) {
    const m = queries[i];
    const missionDir = join(MISSIONS_DIR, m.id);
    await mkdir(missionDir, { recursive: true });
    process.stdout.write(`  ${m.id}…`);

    let urls: string[] = [];
    let saved = 0;
    let hasLegacyCover = false;
    const legacyCoverPath = join(MISSIONS_DIR, `${m.id}.jpg`);
    try {
      urls = await fetchNasaGalleryUrls(m.query, MISSION_GALLERY_MAX);
    } catch {
      // NASA API returned nothing usable. Fall through to Wikimedia
      // single-image cover fallback.
      const fallback = WIKIMEDIA_MISSION_FALLBACK[m.id];
      if (fallback) {
        try {
          const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(fallback)}?width=800`;
          await downloadFromWikimedia(url, join(missionDir, '01.jpg'));
          // Mirror as the legacy cover at static/images/missions/{id}.jpg
          // so existing /missions card paths keep working.
          await downloadFromWikimedia(url, legacyCoverPath);
          saved = 1;
          hasLegacyCover = true;
          process.stdout.write(' wikimedia-cover');
        } catch (err2) {
          const msg = err2 instanceof Error ? err2.message : String(err2);
          process.stdout.write(` ⚠ cover skipped (${msg})`);
        }
      }
    }

    // Download NASA URLs (if any) → 01.jpg, 02.jpg, ...
    for (let n = 0; n < urls.length; n++) {
      const filename = `${String(n + 1).padStart(2, '0')}.jpg`;
      try {
        const imgRes = await fetch(urls[n]);
        if (!imgRes.ok) continue;
        const buffer = Buffer.from(await imgRes.arrayBuffer());
        await writeFile(join(missionDir, filename), buffer);
        if (n === 0) {
          await writeFile(legacyCoverPath, buffer);
          hasLegacyCover = true;
        }
        saved++;
      } catch {
        // Single-image fail; continue with the rest.
      }
    }

    // NASA returned hits but every download failed — same net effect as
    // no imagery; try the single-file Wikimedia cover if configured.
    if (saved === 0 && WIKIMEDIA_MISSION_FALLBACK[m.id]) {
      const fallback = WIKIMEDIA_MISSION_FALLBACK[m.id];
      try {
        const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(fallback)}?width=800`;
        await downloadFromWikimedia(url, join(missionDir, '01.jpg'));
        await downloadFromWikimedia(url, legacyCoverPath);
        saved = 1;
        hasLegacyCover = true;
        process.stdout.write(' wikimedia-cover');
      } catch (err2) {
        const msg = err2 instanceof Error ? err2.message : String(err2);
        process.stdout.write(` ⚠ wikimedia-cover retry skipped (${msg})`);
      }
    }

    // Top up from the curated Wikimedia gallery list when NASA + cover
    // fallback together fell short of MISSION_GALLERY_MAX. This is the
    // path that lifts non-US missions from 1 → 4–5 images.
    if (saved < MISSION_GALLERY_MAX && WIKIMEDIA_MISSION_GALLERY_FALLBACK[m.id]) {
      const after = await topUpWikimediaGallery(
        m.id,
        missionDir,
        saved + 1,
        legacyCoverPath,
        hasLegacyCover,
      );
      if (after > saved) {
        process.stdout.write(` +${after - saved} wikimedia-gallery`);
        saved = after;
      }
    }

    manifest[m.id] = saved;
    totalPhotos += saved;
    process.stdout.write(` ${saved}\n`);

    if (i < queries.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, NASA_API_DELAY_MS));
    }
  }

  // Write the manifest (sorted keys → byte-identical re-runs).
  const sortedManifest: Record<string, number> = {};
  for (const k of Object.keys(manifest).sort()) sortedManifest[k] = manifest[k];
  await writeFile(MISSION_GALLERIES_MANIFEST, JSON.stringify(sortedManifest, null, 2) + '\n');
  const manifestTotal = Object.values(sortedManifest).reduce((a, b) => a + b, 0);
  console.log(
    `  → manifest written to ${MISSION_GALLERIES_MANIFEST} (${manifestTotal} photos total in manifest)`,
  );

  return totalPhotos;
}

// ──────────────────────────────────────────────────────────────────────
// ISS MODULE GALLERIES — NASA Images API + Wikimedia (PRD-010 / ADR-016)
//
// Writes `static/images/iss-modules/{id}/01.jpg` … and
// `static/data/iss-galleries.json` (count map). Mirrors the mission
// gallery flow; Wikimedia fallbacks cover gaps when NASA search fails.
// ──────────────────────────────────────────────────────────────────────

interface IssImageQuery {
  id: string;
  query: string;
}

const ISS_MODULES_IMG_DIR = 'static/images/iss-modules';
const ISS_GALLERIES_MANIFEST = 'static/data/iss-galleries.json';
/** PRD: ~4–8 images per module; 6 balances UX vs bundle size. */
const ISS_GALLERY_MAX = 6;

const ISS_IMAGE_QUERIES: IssImageQuery[] = [
  { id: 'beam', query: 'BEAM expandable module international space station' },
  { id: 'canadarm2', query: 'Canadarm2 space station robotic arm' },
  { id: 'columbus', query: 'Columbus laboratory ISS ESA' },
  { id: 'cupola', query: 'ISS cupola Earth observation windows' },
  { id: 'destiny', query: 'Destiny laboratory ISS module' },
  { id: 'harmony', query: 'Harmony module ISS Node 2' },
  { id: 'kibo', query: 'Kibo Japanese Experiment Module ISS' },
  { id: 'leonardo', query: 'Leonardo PMM permanent multipurpose module ISS' },
  { id: 'nauka', query: 'Nauka science module ISS' },
  { id: 'pirs', query: 'Pirs docking compartment ISS' },
  { id: 'prichal', query: 'Prichal docking module ISS' },
  { id: 'quest', query: 'Quest joint airlock ISS' },
  { id: 'rassvet', query: 'Rassvet ISS module MRM-1' },
  { id: 'tranquility', query: 'Tranquility module ISS Node 3' },
  { id: 'unity', query: 'Unity module ISS Node 1' },
  { id: 'zarya', query: 'Zarya FGB ISS first module' },
  { id: 'zvezda', query: 'Zvezda service module ISS' },
];

/** Single-image Wikimedia cover when NASA search returns nothing usable. */
const WIKIMEDIA_ISS_FALLBACK: Record<string, string> = {
  beam: 'BEAM_module_on_ISS.jpg',
  canadarm2: 'Canadarm2.jpg',
  columbus: 'Columbus_ISS_module.jpg',
  cupola: 'Cupola_ISS.jpg',
  destiny: 'Destiny_module_ISS.jpg',
  harmony: 'Harmony arrives at ISS.jpg',
  kibo: 'Kibō_Japanese_Experiment_Module.jpg',
  leonardo: 'Leonardo PMM module.jpg',
  nauka: 'Anton Shkaplerov works outside Nauka during spacewalk (ISS066-E-119955).jpg',
  pirs: 'Pirs_Iss.jpg',
  prichal: 'The Prichal docking module above Africa.jpg',
  quest: 'Quest_joint_airlock_ISS.jpg',
  rassvet: 'MRM-1 Rassvet during installation.jpg',
  tranquility: 'Tranquility from departing STS-130.jpg',
  unity: 'Unity_(ISS_module)_in_Orbit.jpg',
  zarya: 'Zarya_ISS_module.jpg',
  zvezda: 'Zvezda_ISS.jpg',
};

/** Extra Commons filenames tried first when topping up toward ISS_GALLERY_MAX. */
const WIKIMEDIA_ISS_MODULE_GALLERY: Record<string, string[]> = {
  canadarm2: ['International_Space_Station_after_being_relocated_by_the_Canadarm.jpg'],
  cupola: [
    'EarthObservationCupolaISS052011.jpg',
    'Cupola_at_night.jpg',
    'STS-130 ISS approach closeup of Tranquility and Cupola.jpg',
  ],
  leonardo: [
    'STS-133 ISS-26 Permanent Multipurpose Module.jpg',
    'STS-133 ISS-26 newly-attached Permanent Multipurpose Module.jpg',
    'ISS-43 Permanent Multipurpose Module relocation.jpg',
    'STS-133 Installation PMM 2.jpg',
    'Permanent Multipurpose Module (PMM) Relocation.jpg',
  ],
  nauka: [
    '51651128052 06d3077e33 o Progress MS-17.jpg',
    '1637984492234 Progress MS 17 undocking and Nauka nadir temporary docking adapter Removal 01.jpg',
    'The Nauka multipurpose laboratory module and the Prichal docking module.jpg',
    'ISS-66 Prichal and Nauka during an outfitting spacewalk.jpg',
    'ISS-67 The Nauka and Prichal modules and the Soyuz MS-21 crew ship.jpg',
  ],
  prichal: [
    'Cosmonauts work outside the Prichal module during spacewalk (ISS066-E-121305).jpg',
    'ISS-66 The Nauka multipurpose laboratory module and the Prichal docking module.jpg',
    "Russia's Prichal docking module attached to the Progress delivery vehicle.jpg",
    'Mockup of Prichal Module.jpg',
    "Prichal docked to Nauka (top-left) from today's EVA helmetcam view.jpg",
  ],
  rassvet: [
    'STS-132 ISS-23 Rassvet Pirs and Progress M-05M.jpg',
    'ISS-24 Soyuz TMA-19 Rassvet and Progress M-05M.jpg',
    'ISS-53 Soyuz MS-05 docked to Rassvet above northern central China.jpg',
  ],
  tranquility: ['STS-130 EVA1 Tranquility 1.jpg', 'Node 3 - Isolated view.jpg'],
  harmony: ['ISS Node 2 module.jpg', 'Canadarm2 moving Harmony node into position.jpg'],
};

const ISS_GENERIC_GALLERY_TOPUP: string[] = [
  'International_Space_Station_after_being_relocated_by_the_Canadarm.jpg',
  'International_Space_Station_after_beautiful_day.JPG',
  'ISS_Expedition_42_crew_members_pose_for_an_official_portrait.jpg',
  'NASA_astron_Karen_Nyberg_ISS.jpg',
  'EarthObservationCupolaISS052011.jpg',
  'ISS_and_Shuttle_Endeavour_seen_from_the_Soyuz_TMA-20.jpg',
  'ISS_and_Earth_-_February_2025_(NASA,_ISS088-E-40554).jpg',
];

async function topUpIssWikimediaGallery(
  moduleId: string,
  moduleDir: string,
  nextIndex: number,
): Promise<number> {
  const specific = WIKIMEDIA_ISS_MODULE_GALLERY[moduleId] ?? [];
  const seen = new Set<string>();
  const list: string[] = [];
  for (const f of [...specific, ...ISS_GENERIC_GALLERY_TOPUP]) {
    if (seen.has(f)) continue;
    seen.add(f);
    list.push(f);
  }

  let saved = nextIndex - 1;
  for (const filename of list) {
    if (saved >= ISS_GALLERY_MAX) break;
    const slot = `${String(saved + 1).padStart(2, '0')}.jpg`;
    const dest = join(moduleDir, slot);
    const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(filename)}?width=800`;
    try {
      await downloadFromWikimedia(url, dest);
      saved++;
      await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
    } catch {
      // Skip; try next filename.
    }
  }
  return saved;
}

async function fetchIssModuleImages(onlyIds?: string[]): Promise<number> {
  await mkdir(ISS_MODULES_IMG_DIR, { recursive: true });
  await mkdir('static/data', { recursive: true });

  /** True when `--iss-only=id,id` — merge counts for untouched modules into the manifest. */
  const subsetMode = Array.isArray(onlyIds) && onlyIds.length > 0;

  let prevManifest: Record<string, number> = {};
  if (subsetMode) {
    try {
      prevManifest = JSON.parse(await readFile(ISS_GALLERIES_MANIFEST, 'utf8')) as Record<
        string,
        number
      >;
    } catch {
      /* no existing manifest */
    }
  }
  const manifest: Record<string, number> = subsetMode ? { ...prevManifest } : {};
  let totalPhotos = 0;

  const queries = subsetMode
    ? ISS_IMAGE_QUERIES.filter((q) => onlyIds!.includes(q.id))
    : ISS_IMAGE_QUERIES;

  if (subsetMode && queries.length === 0) {
    console.warn('  ⚠ --iss-only: no ids matched ISS_IMAGE_QUERIES');
    return 0;
  }

  for (let i = 0; i < queries.length; i++) {
    const row = queries[i];
    const moduleDir = join(ISS_MODULES_IMG_DIR, row.id);
    await mkdir(moduleDir, { recursive: true });
    process.stdout.write(`  ${row.id}…`);

    let urls: string[] = [];
    let saved = 0;

    try {
      urls = await fetchNasaGalleryUrls(row.query, ISS_GALLERY_MAX);
    } catch {
      const fallback = WIKIMEDIA_ISS_FALLBACK[row.id];
      if (fallback) {
        try {
          const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(fallback)}?width=800`;
          await downloadFromWikimedia(url, join(moduleDir, '01.jpg'));
          saved = 1;
          process.stdout.write(' wikimedia-cover');
        } catch (err2) {
          const msg = err2 instanceof Error ? err2.message : String(err2);
          process.stdout.write(` ⚠ cover skipped (${msg})`);
        }
      }
    }

    for (let n = 0; n < urls.length; n++) {
      const filename = `${String(n + 1).padStart(2, '0')}.jpg`;
      try {
        const imgRes = await fetch(urls[n]);
        if (!imgRes.ok) continue;
        const buffer = Buffer.from(await imgRes.arrayBuffer());
        await writeFile(join(moduleDir, filename), buffer);
        saved++;
      } catch {
        // Single-image fail; continue with the rest.
      }
    }

    if (saved === 0 && WIKIMEDIA_ISS_FALLBACK[row.id]) {
      const fallback = WIKIMEDIA_ISS_FALLBACK[row.id];
      try {
        const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(fallback)}?width=800`;
        await downloadFromWikimedia(url, join(moduleDir, '01.jpg'));
        saved = 1;
        process.stdout.write(' wikimedia-cover');
      } catch (err2) {
        const msg = err2 instanceof Error ? err2.message : String(err2);
        process.stdout.write(` ⚠ wikimedia-cover retry skipped (${msg})`);
      }
    }

    if (saved < ISS_GALLERY_MAX) {
      const after = await topUpIssWikimediaGallery(row.id, moduleDir, saved + 1);
      if (after > saved) {
        process.stdout.write(` +${after - saved} wikimedia-gallery`);
        saved = after;
      }
    }

    manifest[row.id] = saved;
    totalPhotos += saved;
    process.stdout.write(` ${saved}\n`);

    if (i < queries.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, NASA_API_DELAY_MS));
    }
  }

  const sortedManifest: Record<string, number> = {};
  for (const k of Object.keys(manifest).sort()) sortedManifest[k] = manifest[k];
  await writeFile(ISS_GALLERIES_MANIFEST, JSON.stringify(sortedManifest, null, 2) + '\n');
  const manifestTotal = Object.values(sortedManifest).reduce((a, b) => a + b, 0);
  console.log(
    `  → manifest written to ${ISS_GALLERIES_MANIFEST} (${manifestTotal} photos total in manifest)`,
  );

  return totalPhotos;
}

// ──────────────────────────────────────────────────────────────────────
// PANEL GALLERIES — planets, sun, earth-objects, moon-sites (v0.1.10)
//
// Mirrors the mission-imagery flow but parameterised over category +
// query list + manifest path. Each entity gets up to PANEL_GALLERY_MAX
// photos; the per-category manifest tracks the count so the UI hides
// the GALLERY tab when no photos are available.
//
// For moon-sites whose id matches a mission id (apollo11, change5,
// luna9, etc.) we copy the existing missions/{id}/*.jpg files instead
// of re-downloading — saves bandwidth + keeps galleries consistent.
// ──────────────────────────────────────────────────────────────────────

const PANEL_GALLERY_MAX = 5;

interface GalleryQuery {
  id: string;
  query: string;
  /** When set, skip NASA API and copy images from `static/images/missions/{copyFromMission}/` instead. */
  copyFromMission?: string;
  /** Wikimedia Commons filename used when NASA API returns nothing. */
  wikimediaFallback?: string;
  /** Curated Wikimedia Commons filenames used to top up the gallery
   *  when NASA + single fallback fall short of GALLERY_MIN_TARGET.
   *  Tried in order; missing files are skipped gracefully. */
  wikimediaGallery?: string[];
}

/** Per ADR-016 + #17 follow-up: every panel gallery should carry at
 *  least 3 photos. Lower than NASA's PANEL_GALLERY_MAX so we top up
 *  thin galleries from Wikimedia without overshadowing NASA results. */
const GALLERY_MIN_TARGET = 3;

const PLANET_QUERIES: GalleryQuery[] = [
  { id: 'mercury', query: 'mercury planet messenger' },
  { id: 'venus', query: 'venus planet magellan' },
  { id: 'earth', query: 'earth from space apollo' },
  { id: 'mars', query: 'mars planet rover' },
  { id: 'jupiter', query: 'jupiter great red spot juno' },
  { id: 'saturn', query: 'saturn rings cassini' },
  { id: 'uranus', query: 'uranus voyager' },
  { id: 'neptune', query: 'neptune voyager 2' },
];

const SUN_QUERIES: GalleryQuery[] = [{ id: 'sun', query: 'solar dynamics observatory sun corona' }];

const EARTH_OBJECT_QUERIES: GalleryQuery[] = [
  { id: 'iss', query: 'international space station' },
  {
    id: 'tiangong',
    query: 'tiangong space station china',
    // NASA library credits Tiangong photos to CNSA (filtered out by
    // our credit-allowlist). Top up entirely from Wikimedia. Filenames
    // verified via Commons API search 2026-05-04.
    wikimediaGallery: [
      'Chinese Tiangong Space Station.jpg',
      'Rear view of Tiangong Space Station.jpg',
      'Basic space experiment cabinet of Tiangong space station.jpg',
    ],
  },
  { id: 'hubble', query: 'hubble space telescope' },
  {
    id: 'gps',
    query: 'gps satellite navstar',
    wikimediaFallback: 'Navstar-2F.jpg',
    wikimediaGallery: ['Navstar-2F.jpg', 'GPS_Satellite_NASA_art-iif.jpg', 'ConstellationGPS.gif'],
  },
  {
    id: 'galileo',
    query: 'galileo navigation satellite',
    wikimediaFallback: 'Galileo-IOV-PFM.jpg',
    wikimediaGallery: [
      'Galileo-IOV-PFM.jpg',
      'Galileo satellite model.jpg',
      'Galileo launch on Soyuz, 21 Oct 2011 (6266227357).jpg',
      'Galileo sat constallation.gif',
    ],
  },
  {
    id: 'glonass',
    query: 'glonass satellite',
    wikimediaFallback: 'GLONASS-K_satellite.jpg',
    wikimediaGallery: [
      'GLONASS-K_satellite.jpg',
      'Glonass K model at Cebit 2011 Satellite, sideview 1.jpg',
      'Glonass-receiver.jpg',
      'Comparison satellite navigation orbits.svg',
    ],
  },
  {
    id: 'beidou',
    query: 'beidou navigation satellite',
    wikimediaFallback: 'BeiDou_2.svg',
    wikimediaGallery: [
      'BeiDou_2.svg',
      'Beidou-3 Satellite Mockup.jpg',
      'Chinese news rendering of Beidou satellite.png',
      'Beidou satellite mockup at FING UNLP 03.jpg',
    ],
  },
  { id: 'geo', query: 'geostationary satellite' },
  { id: 'chandra', query: 'chandra x-ray observatory' },
  {
    id: 'xmm',
    query: 'xmm newton x-ray',
    wikimediaFallback: 'XMM-Newton-spacecraft.jpg',
  },
  { id: 'lro', query: 'lunar reconnaissance orbiter', copyFromMission: 'lro' },
  { id: 'jwst', query: 'james webb space telescope' },
  {
    id: 'gaia',
    query: 'gaia spacecraft milky way',
    // NASA library has no official Gaia imagery (ESA mission). Top up
    // entirely from Wikimedia. Filenames verified via Commons API
    // search 2026-05-04.
    wikimediaGallery: [
      'Gaia spacecraft.jpeg',
      'Maquette de Gaia salon du Bourget 2013 DSC 0191.JPG',
      'Gaia spacecraft 360 Gaia Sky.jpg',
    ],
  },
];

const MOON_SITE_QUERIES: GalleryQuery[] = [
  {
    id: 'luna9',
    query: 'luna 9',
    copyFromMission: 'luna9',
    wikimediaGallery: [
      'Luna 9 Space Probe.jpg',
      'Luna 9 proposed 2026 landing site.png',
      'First Photo from the Surface of the Moon.jpg',
    ],
  },
  { id: 'luna17', query: 'lunokhod 1 luna 17', copyFromMission: 'luna17' },
  { id: 'luna24', query: 'luna 24', copyFromMission: 'luna24' },
  { id: 'apollo11', query: 'apollo 11', copyFromMission: 'apollo11' },
  { id: 'apollo12', query: 'apollo 12 lunar surface' },
  { id: 'apollo14', query: 'apollo 14 alan shepard' },
  { id: 'apollo15', query: 'apollo 15 lunar rover' },
  { id: 'apollo16', query: 'apollo 16 descartes' },
  { id: 'apollo17', query: 'apollo 17', copyFromMission: 'apollo17' },
  {
    id: 'change3',
    query: 'chinese chang-e 3 lunar',
    wikimediaFallback: 'Yutu_rover.jpg',
    wikimediaGallery: [
      'Yutu_rover.jpg',
      "Chang'e 3 Lander and Rover From Above (LROC637).gif",
      "Location of the Chang'e-3 landing site.jpg",
      "Chang'e 3 landing site.png",
    ],
  },
  { id: 'change4', query: 'change 4 farside', copyFromMission: 'change4' },
  { id: 'change5', query: 'change 5 lunar', copyFromMission: 'change5' },
  { id: 'change6', query: 'change 6 lunar', copyFromMission: 'change6' },
  { id: 'chandrayaan3', query: 'chandrayaan 3 vikram', copyFromMission: 'chandrayaan3' },
  { id: 'slim', query: 'slim moon lander jaxa', copyFromMission: 'slim' },
  { id: 'artemis3', query: 'artemis lunar landing', copyFromMission: 'artemis3' },
];

/**
 * Generic gallery fetcher. For each entry: copy from missions if
 * configured, otherwise fetch from NASA Images API, finally fall back
 * to the curated Wikimedia filename if both fail. Writes the count
 * manifest so the UI can render thumbnails.
 */
async function fetchPanelGallery(
  label: string,
  queries: GalleryQuery[],
  outputDir: string,
  manifestPath: string,
  manifestShape: 'count-map' | 'singleton',
): Promise<number> {
  await mkdir(outputDir, { recursive: true });
  const manifest: Record<string, number> = {};
  let totalPhotos = 0;

  for (let i = 0; i < queries.length; i++) {
    const q = queries[i];
    const entityDir = manifestShape === 'singleton' ? outputDir : join(outputDir, q.id);
    await mkdir(entityDir, { recursive: true });
    process.stdout.write(`  ${q.id}…`);

    // Path 1 — copy from missions/{id}/ when configured.
    if (q.copyFromMission) {
      const sourceDir = join(MISSIONS_DIR, q.copyFromMission);
      try {
        const files = (await readdir(sourceDir)).filter((f) => /^\d{2}\.jpg$/.test(f)).sort();
        let saved = 0;
        for (const file of files) {
          await copyFile(join(sourceDir, file), join(entityDir, file));
          saved++;
        }
        if (saved > 0) {
          manifest[q.id] = saved;
          totalPhotos += saved;
          process.stdout.write(` copied from missions (${saved})\n`);
          continue;
        }
        process.stdout.write(' no mission images, falling back to NASA…');
      } catch {
        process.stdout.write(' missions/ unavailable, falling back to NASA…');
      }
    }

    // Path 2 — NASA Images API search.
    let urls: string[] = [];
    let saved = 0;
    try {
      urls = await fetchNasaGalleryUrls(q.query, PANEL_GALLERY_MAX);
    } catch {
      // NASA returned nothing usable. Single-image cover via
      // wikimediaFallback comes first; the multi-file wikimediaGallery
      // top-up below brings the total up to GALLERY_MIN_TARGET when
      // available.
      if (q.wikimediaFallback) {
        try {
          const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(q.wikimediaFallback)}?width=800`;
          await downloadFromWikimedia(url, join(entityDir, '01.jpg'));
          saved = 1;
          process.stdout.write(' wikimedia-cover');
        } catch {
          // Fall through to wikimediaGallery top-up below.
        }
      }
    }

    // Download NASA URLs (if any) → 01.jpg, 02.jpg, ...
    for (let n = 0; n < urls.length; n++) {
      const filename = `${String(n + 1).padStart(2, '0')}.jpg`;
      try {
        const imgRes = await fetch(urls[n]);
        if (!imgRes.ok) continue;
        const buffer = Buffer.from(await imgRes.arrayBuffer());
        await writeFile(join(entityDir, filename), buffer);
        saved++;
      } catch {
        // Single-image fail; continue with the rest.
      }
    }

    // Top up from the curated Wikimedia gallery list when NASA + cover
    // fallback fell short of GALLERY_MIN_TARGET. Same shape as
    // topUpWikimediaGallery for missions: filenames tried in order,
    // missing files skipped silently.
    if (saved < GALLERY_MIN_TARGET && q.wikimediaGallery && q.wikimediaGallery.length > 0) {
      const before = saved;
      for (const fname of q.wikimediaGallery) {
        if (saved >= GALLERY_MIN_TARGET) break;
        const slot = `${String(saved + 1).padStart(2, '0')}.jpg`;
        try {
          const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(fname)}?width=800`;
          await downloadFromWikimedia(url, join(entityDir, slot));
          saved++;
        } catch {
          // Skip missing file; continue with the next candidate.
        }
        await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
      }
      if (saved > before) process.stdout.write(` +${saved - before} wikimedia-gallery`);
    }

    if (saved === 0) {
      process.stdout.write(' ⚠ skipped (no images)');
    }

    manifest[q.id] = saved;
    totalPhotos += saved;
    process.stdout.write(` ${saved}\n`);

    if (i < queries.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, NASA_API_DELAY_MS));
    }
  }

  // Write manifest. Singleton shape → `{count: N}`; count-map → sorted `{id: count}`.
  if (manifestShape === 'singleton') {
    const id = queries[0]?.id ?? 'sun';
    const count = manifest[id] ?? 0;
    await writeFile(manifestPath, JSON.stringify({ count }, null, 2) + '\n');
  } else {
    const sorted: Record<string, number> = {};
    for (const k of Object.keys(manifest).sort()) sorted[k] = manifest[k];
    await writeFile(manifestPath, JSON.stringify(sorted, null, 2) + '\n');
  }
  console.log(`  → ${label} manifest: ${manifestPath} (${totalPhotos} photos total)`);
  return totalPhotos;
}

// ──────────────────────────────────────────────────────────────────────
// MISSION TRAJECTORY THUMBNAILS — v0.1.11 / Theme A.A2
//
// 240×120 PNG previews rendered at build time using node-canvas.
// Mars-bound missions get a heliocentric view: Sun, Earth orbit,
// destination orbit, and the outbound arc (uses real V∞ when present
// per mission.flight.arrival.v_infinity_km_s — same code path as
// /explore overlay rings + /fly trajectory).
//
// Moon-bound missions get a cislunar view: Earth at canvas centre +
// Moon orbit ring + a curved arc to a Moon position derived from
// transit_days (matches the /fly Moon-mode geometry).
//
// PNGs land at static/images/missions/thumbnails/{id}.png. Per
// CLAUDE.md ADR-016 these are build-time assets — no runtime canvas
// → image work needed.
// ──────────────────────────────────────────────────────────────────────

const THUMBNAILS_DIR = 'static/images/missions/thumbnails';
const THUMBNAIL_W = 240;
const THUMBNAIL_H = 120;
const THUMBNAIL_PX_PER_AU = 11; // tuned so Saturn (9.5 AU) just fits in width

interface MissionThumbnailRecord {
  id: string;
  dest: Destination;
  color: string;
  departure_date: string;
  transit_days: number;
  flight?: { arrival?: { v_infinity_km_s?: number } };
}

function paintHeliocentricThumbnail(
  ctx: import('canvas').CanvasRenderingContext2D,
  destinationId: DestinationId,
  depDay: number,
  arrivalVInf: number | undefined,
  missionColor: string,
): void {
  const cx = THUMBNAIL_W / 2;
  const cy = THUMBNAIL_H / 2;
  const destA = DESTINATIONS[destinationId].a;

  // Background
  ctx.fillStyle = '#04040c';
  ctx.fillRect(0, 0, THUMBNAIL_W, THUMBNAIL_H);

  // Faint orbit rings (Earth + destination). Auto-clamp scale so the
  // largest orbit fits with margin.
  const maxAu = Math.max(R_EARTH_AU, destA);
  const scale = Math.min(THUMBNAIL_PX_PER_AU, (Math.min(cx, cy) - 8) / maxAu);

  ctx.beginPath();
  ctx.arc(cx, cy, R_EARTH_AU * scale, 0, Math.PI * 2);
  ctx.strokeStyle = 'rgba(75,156,211,0.35)';
  ctx.lineWidth = 0.6;
  ctx.stroke();
  ctx.beginPath();
  ctx.arc(cx, cy, destA * scale, 0, Math.PI * 2);
  ctx.strokeStyle = missionColor;
  ctx.globalAlpha = 0.35;
  ctx.lineWidth = 0.6;
  ctx.stroke();
  ctx.globalAlpha = 1;

  // Sun
  ctx.fillStyle = '#fff8c0';
  ctx.beginPath();
  ctx.arc(cx, cy, 2.5, 0, Math.PI * 2);
  ctx.fill();

  // Outbound arc — same code path as /fly + /explore overlay
  const earthDep = earthPos(depDay);
  const arc = outboundArc(earthDep, 80, destA, arrivalVInf);

  ctx.beginPath();
  arc.forEach((p, i) => {
    const x = cx + p.x * scale;
    const y = cy + p.z * scale;
    if (i === 0) ctx.moveTo(x, y);
    else ctx.lineTo(x, y);
  });
  ctx.strokeStyle = missionColor;
  ctx.lineWidth = 1.4;
  ctx.shadowColor = missionColor;
  ctx.shadowBlur = 4;
  ctx.stroke();
  ctx.shadowBlur = 0;

  // Departure node (teal) + arrival node (gold)
  const dep = arc[0];
  const arr = arc[arc.length - 1];
  ctx.fillStyle = '#4ecdc4';
  ctx.beginPath();
  ctx.arc(cx + dep.x * scale, cy + dep.z * scale, 2.5, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#ffc850';
  ctx.beginPath();
  ctx.arc(cx + arr.x * scale, cy + arr.z * scale, 2.5, 0, Math.PI * 2);
  ctx.fill();
}

function paintCislunarThumbnail(
  ctx: import('canvas').CanvasRenderingContext2D,
  transitDays: number,
  missionColor: string,
): void {
  const cx = THUMBNAIL_W * 0.32;
  const cy = THUMBNAIL_H / 2;
  const moonRadiusPx = 70; // visual

  // Background
  ctx.fillStyle = '#04040c';
  ctx.fillRect(0, 0, THUMBNAIL_W, THUMBNAIL_H);

  // Moon orbit ring (centred on Earth)
  ctx.beginPath();
  ctx.arc(cx, cy, moonRadiusPx, 0, Math.PI * 2);
  ctx.strokeStyle = 'rgba(170,170,204,0.3)';
  ctx.lineWidth = 0.6;
  ctx.stroke();

  // Earth
  ctx.fillStyle = '#3a8fcc';
  ctx.beginPath();
  ctx.arc(cx, cy, 4, 0, Math.PI * 2);
  ctx.fill();

  // Moon — position derived from transit_days (so Apollo 11's 4-day
  // transit and SLIM's 135-day transit render at distinct angles).
  const moonAngle = ((transitDays % 27.32) / 27.32) * Math.PI * 2;
  const moonX = cx + Math.cos(moonAngle) * moonRadiusPx;
  const moonY = cy + Math.sin(moonAngle) * moonRadiusPx;
  ctx.fillStyle = '#cfcfcf';
  ctx.beginPath();
  ctx.arc(moonX, moonY, 3, 0, Math.PI * 2);
  ctx.fill();

  // Quadratic-Bezier arc Earth → Moon (same shape as /fly Moon-mode)
  const ctrlX = (cx + moonX) / 2 + (cy - moonY) * 0.18;
  const ctrlY = (cy + moonY) / 2 + (moonX - cx) * 0.18;
  ctx.beginPath();
  ctx.moveTo(cx, cy);
  ctx.quadraticCurveTo(ctrlX, ctrlY, moonX, moonY);
  ctx.strokeStyle = missionColor;
  ctx.lineWidth = 1.4;
  ctx.shadowColor = missionColor;
  ctx.shadowBlur = 4;
  ctx.stroke();
  ctx.shadowBlur = 0;

  // Departure node + arrival node
  ctx.fillStyle = '#4ecdc4';
  ctx.beginPath();
  ctx.arc(cx, cy, 2.5, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#ffc850';
  ctx.beginPath();
  ctx.arc(moonX, moonY, 2.5, 0, Math.PI * 2);
  ctx.fill();
}

async function fetchMissionThumbnails(): Promise<number> {
  await mkdir(THUMBNAILS_DIR, { recursive: true });
  let saved = 0;

  const rootEntries = await readdir('static/data/missions', { withFileTypes: true });
  const destDirs = rootEntries.filter((e) => e.isDirectory()).map((e) => e.name);

  for (const dest of destDirs) {
    const dir = `static/data/missions/${dest}`;
    const files = (await readdir(dir)).filter((f) => f.endsWith('.json'));
    for (const file of files) {
      const raw = await readFile(join(dir, file), 'utf8');
      const m = JSON.parse(raw) as MissionThumbnailRecord;
      const canvas = createCanvas(THUMBNAIL_W, THUMBNAIL_H);
      const ctx = canvas.getContext('2d');
      const depDay = dateToSimDay(m.departure_date) ?? 0;
      const color = m.color || '#4ecdc4';

      if (m.dest === 'MOON') {
        paintCislunarThumbnail(ctx, m.transit_days, color);
      } else {
        const hid = missionDestToHeliocentricDestinationId(m.dest);
        if (!hid) {
          throw new Error(
            `Thumbnail: mission ${m.id} has dest ${m.dest} without heliocentric mapping`,
          );
        }
        const vInf = m.flight?.arrival?.v_infinity_km_s;
        paintHeliocentricThumbnail(ctx, hid, depDay, vInf, color);
      }

      const buffer = canvas.toBuffer('image/png');
      await writeFile(join(THUMBNAILS_DIR, `${m.id}.png`), buffer);
      saved++;
      process.stdout.write(`  ${m.id} `);
    }
  }

  process.stdout.write('\n');
  console.log(`  → ${saved} thumbnails written to ${THUMBNAILS_DIR}`);
  return saved;
}

// ──────────────────────────────────────────────────────────────────────
// SHARED HELPERS
// ──────────────────────────────────────────────────────────────────────

async function downloadFile(url: string, dest: string): Promise<void> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: HTTP ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buffer);
}

// ──────────────────────────────────────────────────────────────────────
// MAIN
// ──────────────────────────────────────────────────────────────────────

async function main() {
  const issOnlyArg = process.argv.find((a) => a === '--iss-only' || a.startsWith('--iss-only='));
  let issOnlyIds: string[] | undefined;
  if (issOnlyArg) {
    if (issOnlyArg === '--iss-only') {
      issOnlyIds = undefined;
    } else {
      const parts = issOnlyArg
        .slice('--iss-only='.length)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);
      issOnlyIds = parts.length > 0 ? parts : undefined;
    }
  }

  if (issOnlyArg) {
    console.log(
      issOnlyIds?.length
        ? `ISS module subset (${issOnlyIds.join(', ')}) — skipping fonts/textures/etc.\n`
        : 'ISS module galleries only — skipping fonts/textures/etc.\n',
    );
    const issPhotos = await fetchIssModuleImages(issOnlyIds);
    console.log(`  → ${issPhotos} ISS gallery files accounted for in manifest\n`);
    console.log('Done.');
    return;
  }

  const missionsOnlyArg = process.argv.find((a) => a.startsWith('--missions-only='));
  const missionsOnly = missionsOnlyArg
    ? missionsOnlyArg
        .slice('--missions-only='.length)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
    : undefined;

  if (missionsOnly?.length) {
    console.log(
      `Mission subset mode (${missionsOnly.join(', ')}) — skipping fonts/textures/etc.\n`,
    );
    const missionCount = await fetchMissionImages(missionsOnly);
    console.log(`  → ${missionCount} new/changed mission gallery files written\n`);
    console.log('Rendering mission trajectory thumbnails:');
    await fetchMissionThumbnails();
    console.log('');
    console.log('Done.');
    return;
  }

  console.log('Fetching fonts:');
  const fontCount = await fetchFonts();
  console.log(`  → ${fontCount} woff2 files; wrote ${FONTS_CSS_OUT}\n`);

  console.log('Fetching textures:');
  const textureCount = await fetchTextures();
  console.log(`  → ${textureCount} texture files in ${TEXTURES_DIR}\n`);

  console.log('Fetching lunar disc photos:');
  const lunarCount = await fetchLunarDiscPhotos();
  console.log(`  → ${lunarCount} lunar disc files in ${TEXTURES_DIR}\n`);

  console.log('Fetching agency logos:');
  const logoCount = await fetchAgencyLogos();
  console.log(`  → ${logoCount} logo files in ${LOGOS_DIR}\n`);

  console.log('Fetching rocket imagery:');
  const rocketCount = await fetchRocketImages();
  console.log(`  → ${rocketCount} rocket files in ${ROCKETS_DIR}\n`);

  console.log('Fetching mission imagery (NASA Images API):');
  const missionCount = await fetchMissionImages();
  console.log(`  → ${missionCount} mission files in ${MISSIONS_DIR}\n`);

  console.log('Fetching planet galleries:');
  await fetchPanelGallery(
    'planets',
    PLANET_QUERIES,
    'static/images/planets',
    'static/data/planet-galleries.json',
    'count-map',
  );
  console.log('');

  console.log('Fetching sun gallery:');
  await fetchPanelGallery(
    'sun',
    SUN_QUERIES,
    'static/images/sun',
    'static/data/sun-gallery.json',
    'singleton',
  );
  console.log('');

  console.log('Fetching earth-object galleries:');
  await fetchPanelGallery(
    'earth-objects',
    EARTH_OBJECT_QUERIES,
    'static/images/earth-objects',
    'static/data/earth-object-galleries.json',
    'count-map',
  );
  console.log('');

  console.log('Fetching moon-site galleries:');
  await fetchPanelGallery(
    'moon-sites',
    MOON_SITE_QUERIES,
    'static/images/moon-sites',
    'static/data/moon-site-galleries.json',
    'count-map',
  );
  console.log('');

  console.log('Fetching ISS module galleries:');
  const issGalleryTotal = await fetchIssModuleImages();
  console.log(`  → ${issGalleryTotal} ISS module gallery files in ${ISS_MODULES_IMG_DIR}\n`);

  console.log('Rendering mission trajectory thumbnails:');
  await fetchMissionThumbnails();
  console.log('');

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
