/**
 * Fetches external assets at build time per ADR-016.
 *
 * Slice 1: Google Fonts (Bebas Neue, Space Mono, Crimson Pro).
 * Slice 3: planet textures + moon texture from Solar System Scope.
 * v0.1.x patches: agency logos from Wikimedia Commons.
 * Future: NASA Images API for per-mission imagery; rocket reference imagery.
 *
 * Run via: npm run fetch-assets
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';

// ──────────────────────────────────────────────────────────────────────
// FONTS — Slice 1
// ──────────────────────────────────────────────────────────────────────

interface FontDef {
  family: string;
  cssParam: string;
}

const FONTS: FontDef[] = [
  { family: 'Bebas Neue', cssParam: 'Bebas+Neue' },
  { family: 'Space Mono', cssParam: 'Space+Mono:wght@400;700' },
  { family: 'Crimson Pro', cssParam: 'Crimson+Pro:ital,wght@0,400;0,600;1,400' },
];

const FONT_BASE_URL = 'https://fonts.googleapis.com/css2';
// User-Agent that triggers woff2 responses from Google Fonts.
const FONT_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FONTS_DIR = 'static/fonts';
const FONTS_CSS_OUT = 'src/lib/styles/fonts.css';

async function fetchFontCss(font: FontDef): Promise<string> {
  const url = `${FONT_BASE_URL}?family=${font.cssParam}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': FONT_UA } });
  if (!res.ok) throw new Error(`Failed to fetch CSS for ${font.family}: HTTP ${res.status}`);
  return res.text();
}

function extractWoff2Urls(css: string): Set<string> {
  const urls = new Set<string>();
  const regex = /url\((https:\/\/[^)]+\.woff2)\)/g;
  let match;
  while ((match = regex.exec(css)) !== null) {
    urls.add(match[1]);
  }
  return urls;
}

async function fetchFonts(): Promise<number> {
  await mkdir(FONTS_DIR, { recursive: true });
  await mkdir(dirname(FONTS_CSS_OUT), { recursive: true });

  let combinedCss =
    '/* Auto-generated by scripts/fetch-assets.ts. Do not edit by hand.\n' +
    '   Re-run with: npm run fetch-assets */\n\n';
  let downloaded = 0;

  for (const font of FONTS) {
    console.log(`  ${font.family}…`);
    const css = await fetchFontCss(font);
    const urls = extractWoff2Urls(css);

    let localCss = css;
    for (const url of urls) {
      const filename = url.split('/').pop();
      if (!filename) throw new Error(`Could not derive filename from ${url}`);
      const localPath = join(FONTS_DIR, filename);
      await downloadFile(url, localPath);
      localCss = localCss.replaceAll(url, `/fonts/${filename}`);
      downloaded++;
    }

    combinedCss += `/* ${font.family} */\n${localCss}\n`;
  }

  await writeFile(FONTS_CSS_OUT, combinedCss);
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// PLANET + MOON TEXTURES — Slice 3
//
// Source: Solar System Scope (https://www.solarsystemscope.com/textures/)
// Licence: CC BY 4.0. Attribution: "Solar System Scope" in mission-credits page.
// 2K resolution chosen as a balance of detail and bundle size (~3 MB total).
// Issue #3 originally pointed at three.js's r128 examples/textures/planets/
// folder, which doesn't actually contain 2k_*.jpg files in r128 — only Earth
// and Moon textures. SSS is the canonical source for the full set.
// ──────────────────────────────────────────────────────────────────────

const TEXTURE_BASE_URL = 'https://www.solarsystemscope.com/textures/download';

const TEXTURES = [
  '2k_sun.jpg',
  '2k_mercury.jpg',
  '2k_venus_atmosphere.jpg',
  '2k_earth_daymap.jpg',
  '2k_mars.jpg',
  '2k_jupiter.jpg',
  '2k_saturn.jpg',
  '2k_uranus.jpg',
  '2k_neptune.jpg',
  '2k_moon.jpg',
];

const TEXTURES_DIR = 'static/textures';

async function fetchTextures(): Promise<number> {
  await mkdir(TEXTURES_DIR, { recursive: true });
  let downloaded = 0;
  for (const filename of TEXTURES) {
    console.log(`  ${filename}…`);
    const url = `${TEXTURE_BASE_URL}/${filename}`;
    const localPath = join(TEXTURES_DIR, filename);
    await downloadFile(url, localPath);
    downloaded++;
  }
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// AGENCY LOGOS — v0.1.x patch
//
// Source: Wikimedia Commons. All listed logos are public domain (NASA,
// ESA, JAXA, ISRO, ROSCOSMOS, CNSA — government symbols / agency
// emblems) or PD-trivial (SpaceX wordmark). License compliance per
// ADR-016: no third-party runtime dependencies; logos fetched at build
// and committed.
//
// If Wikimedia changes a file path, the fetch will fail gracefully —
// this script logs a warning and continues. The UI falls back to a
// text-only agency badge when an image is missing.
// ──────────────────────────────────────────────────────────────────────

interface AgencyLogo {
  id: string;
  /**
   * Wikimedia Commons filename (case-sensitive, must include extension).
   * Resolved via Special:FilePath which is stable across hash-bucket
   * moves — direct upload.wikimedia.org URLs change when files are
   * recategorised.
   */
  filename: string;
  ext: 'svg' | 'png';
  license: string;
}

const AGENCY_LOGOS: AgencyLogo[] = [
  {
    id: 'nasa',
    filename: 'NASA_logo.svg',
    ext: 'svg',
    license: 'Public domain (US Government work)',
  },
  {
    id: 'esa',
    filename: 'ESA_logo_simple.svg',
    ext: 'svg',
    license: 'Permissive — ESA agency emblem',
  },
  {
    id: 'roscosmos',
    filename: 'Roscosmos_logo_en.svg',
    ext: 'svg',
    license: 'Public domain (Russian Federal Space Agency)',
  },
  {
    id: 'cnsa',
    filename: 'Insignia_of_CNSA.svg',
    ext: 'svg',
    license: 'Public domain (PRC government)',
  },
  {
    id: 'isro',
    filename: 'Indian_Space_Research_Organisation_Logo.svg',
    ext: 'svg',
    license: 'Public domain (Government of India)',
  },
  {
    id: 'jaxa',
    filename: 'Jaxa_logo.svg',
    ext: 'svg',
    license: 'Public domain (Japanese government agency)',
  },
  {
    id: 'spacex',
    filename: 'SpaceX-Logo.svg',
    ext: 'svg',
    license: 'PD-trivial (simple wordmark)',
  },
  {
    id: 'uaesa',
    filename: 'UAE_Space_Agency_logo.svg',
    ext: 'svg',
    license: 'Permissive — UAE agency emblem',
  },
];

const WIKIMEDIA_FILEPATH_BASE = 'https://commons.wikimedia.org/wiki/Special:FilePath';

const LOGOS_DIR = 'static/logos';

// Wikimedia requires a descriptive User-Agent (not a generic
// HTTP-client UA) and rate-limits anonymous bulk downloads. The
// guidance is roughly one request per second for scripts.
const WIKIMEDIA_UA =
  'OrreryBuildBot/0.1 (https://github.com/chipi/orrery; contact: marko.dragoljevic@gmail.com)';
const WIKIMEDIA_DELAY_MS = 1100;

async function downloadFromWikimedia(url: string, dest: string): Promise<void> {
  const res = await fetch(url, { headers: { 'User-Agent': WIKIMEDIA_UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buffer);
}

async function fetchAgencyLogos(): Promise<number> {
  await mkdir(LOGOS_DIR, { recursive: true });
  let downloaded = 0;
  for (let i = 0; i < AGENCY_LOGOS.length; i++) {
    const logo = AGENCY_LOGOS[i];
    const localPath = join(LOGOS_DIR, `${logo.id}.${logo.ext}`);
    const url = `${WIKIMEDIA_FILEPATH_BASE}/${encodeURIComponent(logo.filename)}`;
    console.log(`  ${logo.id}.${logo.ext}…`);
    try {
      await downloadFromWikimedia(url, localPath);
      downloaded++;
    } catch (err) {
      // Don't break the build for a missing logo. Wikimedia URLs
      // occasionally rename files; log and continue. The UI degrades
      // gracefully to text-only badges.
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`    ⚠ skipped ${logo.id}: ${msg}`);
    }
    // Throttle to stay under Wikimedia's anonymous-script rate limit.
    if (i < AGENCY_LOGOS.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, WIKIMEDIA_DELAY_MS));
    }
  }
  return downloaded;
}

// ──────────────────────────────────────────────────────────────────────
// SHARED HELPERS
// ──────────────────────────────────────────────────────────────────────

async function downloadFile(url: string, dest: string): Promise<void> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: HTTP ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buffer);
}

// ──────────────────────────────────────────────────────────────────────
// MAIN
// ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('Fetching fonts:');
  const fontCount = await fetchFonts();
  console.log(`  → ${fontCount} woff2 files; wrote ${FONTS_CSS_OUT}\n`);

  console.log('Fetching textures:');
  const textureCount = await fetchTextures();
  console.log(`  → ${textureCount} texture files in ${TEXTURES_DIR}\n`);

  console.log('Fetching agency logos:');
  const logoCount = await fetchAgencyLogos();
  console.log(`  → ${logoCount} logo files in ${LOGOS_DIR}\n`);

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
