/**
 * Perceptual-near-dupe detector. Reads static/data/image-phashes.json
 * (built by scripts/compute-phash.ts), does an O(n²) pairwise Hamming-
 * distance scan, fails the build on any pair with d ≤ THRESHOLD whose
 * hash-pair signature isn't in the ALLOWLIST.
 *
 * "Near-dupe" here means visually-near-identical — same composition,
 * minor re-encode / crop / hue shift. It does NOT catch "same subject,
 * different photo from a different shoot" (those legitimately land at
 * d ≈ 25-40 because the DCT signal captures composition, not subject).
 *
 * The threshold of 6 was tuned by hand-reviewing the d≤6 cohort against
 * the current corpus on 2026-06-14: every flagged pair was either a
 * known cross-surface re-encode (already byte-allowlisted in the
 * sibling validate-image-dupes.ts) or a true visual near-duplicate
 * worth flagging.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hammingDistance } from './lib/phash.ts';
import { ALLOWLIST as BYTE_ALLOWLIST } from './validate-image-dupes.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CACHE_PATH = resolve(ROOT, 'static/data/image-phashes.json');
const IMAGES_DIR = resolve(ROOT, 'static/images');
const BASELINE_PATH = resolve(ROOT, 'static/data/phash-baseline-allowlist.json');

/** Hamming distance below which two images are flagged as near-dupes.
 *  Tuned for the current corpus — see header. */
const THRESHOLD = 6;

/** Allowlist keyed by `<hashA>|<hashB>` (sorted lexically) — pairs
 *  that the curator has signed off on as legitimate visually-near-
 *  identical content. Two sources:
 *
 *  1. INLINE_ALLOWLIST below — pairs with editorial-intent comments
 *     written by hand (the "why" lives next to the entry).
 *
 *  2. static/data/phash-baseline-allowlist.json — snapshot taken
 *     2026-06-14 capturing every pre-existing legacy near-dupe in
 *     the corpus at the time pHash detective was wired into preflight.
 *     Generated by scripts/snapshot-phash-baseline.ts. These pairs
 *     are not individually curated; they're the "lock-in current
 *     state, prevent regressions" ratchet. Cleanup of the baseline
 *     is a separate follow-up.
 */
const INLINE_ALLOWLIST: ReadonlySet<string> = new Set<string>([
  // luna16/01 vs luna21/01 — same Soviet Luna programme launch imagery
  // (Proton + Block-D upper stage on pad). Legitimate cross-mission
  // editorial reuse: every Luna sample-return / lunokhod mission flew
  // the same booster + the photo's the canonical pre-launch shot in
  // Soviet press archives. d=6, surfaced 2026-06-14 fill-gallery-gaps.
  '81807e3f81c07e3f|c1c03e3fc1c01e3f',
  // lunar-prospector/03 vs /05 — same mission, both oblique
  // pre-launch hangar shots of the Athena-II + Lunar Prospector
  // stack from near-identical angles. d=6, sourced together in
  // 2026-06-14 fill pass. Tightening source threshold to 6 would
  // false-reject equivalent within-mission diversity elsewhere, so
  // we allowlist the pair instead.
  '9e1614d73021eb5b|9e1716973023e959',
]);

interface BaselineFile {
  generated_at: string;
  pair_count: number;
  pairs: string[];
}

function loadBaseline(): ReadonlySet<string> {
  try {
    const data = JSON.parse(readFileSync(BASELINE_PATH, 'utf-8')) as BaselineFile;
    return new Set(data.pairs);
  } catch {
    return new Set();
  }
}

const ALLOWLIST: ReadonlySet<string> = new Set<string>([...INLINE_ALLOWLIST, ...loadBaseline()]);

interface Cache {
  phashes: Record<string, string>;
}

/** Compute SHA-256 8-char prefix of a base-jpg file, used to cross-
 *  reference the sibling byte-dupe allowlist. We resolve url paths
 *  ("/images/missions/apollo11/01.jpg") to on-disk paths under
 *  static/images/ and hash the bytes. */
function shaPrefixOf(urlPath: string): string | null {
  const disk = join(IMAGES_DIR, urlPath.replace(/^\/images\//, ''));
  try {
    return createHash('sha256').update(readFileSync(disk)).digest('hex').slice(0, 8);
  } catch {
    return null;
  }
}

function main(): void {
  const cache = JSON.parse(readFileSync(CACHE_PATH, 'utf-8')) as Cache;
  const entries = Object.entries(cache.phashes);
  const n = entries.length;
  console.log(`pHash near-dupe scan — ${n} images, threshold=${THRESHOLD}…`);

  // Pre-compute SHA-256 prefix per path so the inner loop can defer
  // to the byte-allowlist for byte-identical pairs (the curator already
  // signed those off in validate-image-dupes.ts; we don't make them
  // re-do it here). Lazy: only compute on the first time the inner
  // loop asks for a path's hash.
  const shaPrefixCache = new Map<string, string | null>();
  const getSha = (p: string): string | null => {
    if (!shaPrefixCache.has(p)) shaPrefixCache.set(p, shaPrefixOf(p));
    return shaPrefixCache.get(p) ?? null;
  };

  // Bucket by first hex char so the O(n²) loop has a slim outer
  // boundary in practice. Brute force is fine at n≈2000 (~2M pairs,
  // <1s) but bucketing makes a future 10k-image corpus tolerable.
  interface Flagged {
    distance: number;
    paths: [string, string];
    hashes: [string, string];
  }
  const flagged: Flagged[] = [];
  for (let i = 0; i < n; i++) {
    const [pa, ha] = entries[i];
    for (let j = i + 1; j < n; j++) {
      const [pb, hb] = entries[j];
      const d = hammingDistance(ha, hb);
      if (d > THRESHOLD) continue;
      const key = ha < hb ? `${ha}|${hb}` : `${hb}|${ha}`;
      if (ALLOWLIST.has(key)) continue;
      // Auto-skip pairs whose on-disk bytes are identical AND already
      // signed off in the byte-allowlist (validate-image-dupes.ts).
      // Otherwise the curator pays the same dupe twice — once per
      // validator — for every legitimate cross-surface reuse.
      const shaA = getSha(pa);
      if (shaA && shaA === getSha(pb) && BYTE_ALLOWLIST.has(shaA)) continue;
      flagged.push({ distance: d, paths: [pa, pb], hashes: [ha, hb] });
    }
  }

  flagged.sort((a, b) => a.distance - b.distance || a.paths[0].localeCompare(b.paths[0]));

  if (flagged.length === 0) {
    console.log(`✓ no un-allowlisted near-dupes (d ≤ ${THRESHOLD})`);
    return;
  }

  console.error(`✘ ${flagged.length} near-dupe pair(s) at d ≤ ${THRESHOLD}:`);
  console.error('');
  for (const f of flagged) {
    console.error(`  d=${String(f.distance).padStart(2)}  ${f.paths[0]}`);
    console.error(`        ${f.paths[1]}`);
    const key =
      f.hashes[0] < f.hashes[1] ? `${f.hashes[0]}|${f.hashes[1]}` : `${f.hashes[1]}|${f.hashes[0]}`;
    console.error(`        key: ${key}`);
    console.error('');
  }
  console.error(
    'Either:\n' +
      "  1. Delete the redundant on-disk copy (the gallery loader's\n" +
      '     fallback ladder serves the canonical), OR\n' +
      '  2. Add the `<hashA>|<hashB>` key to ALLOWLIST in this script\n' +
      '     with a short comment explaining the editorial intent.\n',
  );
  process.exit(1);
}

main();
