/**
 * Perceptual-near-dupe detector. Reads static/data/image-phashes.json
 * (built by scripts/compute-phash.ts), does an O(n²) pairwise Hamming-
 * distance scan, fails the build on any pair with d ≤ THRESHOLD whose
 * hash-pair signature isn't in the ALLOWLIST.
 *
 * "Near-dupe" here means visually-near-identical — same composition,
 * minor re-encode / crop / hue shift. It does NOT catch "same subject,
 * different photo from a different shoot" (those legitimately land at
 * d ≈ 25-40 because the DCT signal captures composition, not subject).
 *
 * The threshold of 6 was tuned by hand-reviewing the d≤6 cohort against
 * the current corpus on 2026-06-14: every flagged pair was either a
 * known cross-surface re-encode (already byte-allowlisted in the
 * sibling validate-image-dupes.ts) or a true visual near-duplicate
 * worth flagging.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hammingDistance } from './lib/phash.ts';
import { ALLOWLIST as BYTE_ALLOWLIST } from './validate-image-dupes.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CACHE_PATH = resolve(ROOT, 'static/data/image-phashes.json');
const IMAGES_DIR = resolve(ROOT, 'static/images');
const BASELINE_PATH = resolve(ROOT, 'static/data/phash-baseline-allowlist.json');

/** Hamming distance below which two images are flagged as near-dupes.
 *  Tuned for the current corpus — see header. */
const THRESHOLD = 6;

/** Allowlist keyed by `<hashA>|<hashB>` (sorted lexically) — pairs
 *  that the curator has signed off on as legitimate visually-near-
 *  identical content. Two sources:
 *
 *  1. INLINE_ALLOWLIST below — categorized editorial-reuse pairs
 *     migrated 2026-06-14 from the auto-generated baseline. Grouped
 *     by programme / surface-pattern so the "why" is shared across
 *     a related cohort.
 *
 *  2. static/data/phash-baseline-allowlist.json — residual snapshot
 *     of pairs the categorizer couldn't bucket into a named
 *     programme (cross-entity edge cases, orphan hashes, generic
 *     "other"). These hold the line until a curator hand-reviews +
 *     promotes them into the inline groups or deletes the redundant
 *     copy. Generated by scripts/snapshot-phash-baseline.ts.
 */
const INLINE_ALLOWLIST: ReadonlySet<string> = new Set<string>([
  // luna16/01 vs luna21/01 — same Soviet Luna programme launch imagery
  // (Proton + Block-D upper stage on pad). Legitimate cross-mission
  // editorial reuse: every Luna sample-return / lunokhod mission flew
  // the same booster + the photo's the canonical pre-launch shot in
  // Soviet press archives. d=6, surfaced 2026-06-14 fill-gallery-gaps.
  '81807e3f81c07e3f|c1c03e3fc1c01e3f',
  // lunar-prospector/03 vs /05 — same mission, both oblique
  // pre-launch hangar shots of the Athena-II + Lunar Prospector
  // stack from near-identical angles. d=6, sourced together in
  // 2026-06-14 fill pass. Tightening source threshold to 6 would
  // false-reject equivalent within-mission diversity elsewhere, so
  // we allowlist the pair instead.
  '9e1614d73021eb5b|9e1716973023e959',

  // ----- canonical-cross-surface (73 pairs) -----
  // Cross-surface re-encode of the SAME entity (mission/satellite/site
  // surfaced on two routes). Editorial intent: surface-aware presentation
  // of one canonical asset. Bytes differ only because each fetch re-encoded
  // the same Commons source.
  '00cf84ff840f3cf1|00cf84ff840f3cf1', // mro
  '04990766f3919c6f|04990766f3919c6f', // mro
  '058de18d1467f339|859de18d1463d339', // bepicolombo
  '0b0b4b5a1e8e86db|0b0b4b5a9e8e82db', // beresheet
  '0dcc93c2b67a4d07|0dcc93c2b67a4d07', // venera-13
  '0fcdd8333ccc0963|0fcdd8333ccc0963', // giotto
  '1133c0ee8c0dcddb|1133c0ee8c0dcddb', // mangalyaan
  '166985098579d779|166985098579d779', // insight
  '167b0ca985f90739|167b0ca985f90739', // insight
  '190977c61f11a9e5|990977c60f11a9e5', // mars2
  '1c867707e319c939|1c867707e319c939', // mars-pathfinder
  '1cc271648e93717d|9cc071648e93717d', // curiosity
  '1e7e7ef4c1d40103|1e7e7ef4c1d40103', // voyager-2
  '24f51ef6b40e4a89|24f51ef6b40e4a89', // mro
  '291b395b59634785|291b395b59634785', // blue-moon-mk1
  '30c78b0e663c71e3|30c78b0e663c71e3', // mars2
  '32e3244edc36d2a9|32e3244edc36d2a9', // insight
  '33c994969a49f127|33c994969a49f127', // curiosity
  '34c33fcb8509c13d|34c33fcb8509c13d', // insight
  '37474ce19e1b23c1|37474ce19e1b23c1', // perseverance
  '382bd9a79a460739|382bd9a79a460739', // mars6
  '38910e9151798feb|38910e9151798feb', // perseverance
  '3b0123e1ce1ef1a3|3b0923e1ce1eb1a3', // bepicolombo
  '4670ba93c769a983|4670ba93c769a983', // voyager-2
  '4d9c6937926295c9|4d9c6937926295c9', // schiaparelli
  '4f1a323267e5149d|4f1a3232e7a5149d', // beidou
  '510c196333d147bf|510c196333d147bf', // venera-13
  '515b73aa6989a427|515b73aa6989a427', // curiosity
  '562fe56239356445|562fe56239356445', // starliner
  '58b6672718d49749|58b6672718d49749', // voyager-1
  '63529a9332236bab|63529a9332236bab', // perseverance
  '6558cf44b967d821|6558cf44b967d821', // chandrayaan1
  '666ce6a493961969|666ce6a493961969', // mangalyaan
  '66a62696b65299a9|66a62696b65299a9', // maven
  '682d32c47623af95|682d32c47623af95', // change6
  '74531bac4547da29|74531bac4547da29', // mars-express
  '7579a6492e9c5429|7579a6492e9c5429', // maven
  '7633cd2698cc2533|7633cd2698cc2533', // dawn
  '79d903341c4e94f5|79d903341c4e94f5', // maven
  '81de477679f42c01|81de477679f42c01', // maven
  '83a0b87f79708707|83a0b87f79708707', // voyager-1
  '86de86581e797883|86de86581e797883', // voyager-2
  '8b36cd0549f63e81|8b36cd0549f63e81', // mro
  '8d45a555b8d4a333|8d47a555b8d4a233', // luna24
  '925e125683716d8f|b85e127683616d8d', // lunar-prospector
  '94477897944f03b3|94477897944f03b3', // luna24
  '95845cc1965ae52f|95845cc1965ae52f', // curiosity
  '95ccd1385523961f|95ccd1385523961f', // voyager-1
  '96d635b1886836b5|96d635b1886836b5', // apollo15
  'a1db06c87c8731a7|a1db06c87c8731a7', // viking2-lander
  'a30784199ab1db57|a30784199ab1db57', // galileo
  'a6fa20878f5079a9|a6fa20878f5079a9', // voyager-1
  'a793197cc89c542b|b793197c489c542b', // juno
  'a9694ada923266cd|a9694ada923266cd', // mars-express
  'ad065e7eff020291|ad065e7eff020291', // beagle2
  'ada9284a4a92b76d|ada9284a4a92b76d', // mars-express
  'b1a38da17c814977|b1a38da17c814977', // blue-moon-mk1
  'b6038ea983837c57|b6038ea983837c57', // mars2
  'c01ea9723bc1cd2d|c81ca9723bc1cd2d', // ulysses
  'c51ae4d421765ea9|c51ae4d421765ea9', // mars3
  'c6231a83930bad7d|c6231a83930bad7d', // mars6
  'c83649b40bd1bd2b|c83649b40bd1bd2b', // perseverance
  'cc5229da634c9e33|cc72299a634c9e33', // ulysses
  'cca9a30269aba8bd|cca9a30269aba8bd', // change6
  'e03b86f0584b93e5|e03b86f0584b93e5', // mangalyaan
  'e04d49695c67a197|e04d49695c67a197', // curiosity
  'e1923ca018ede71b|e1923ca018ede71b', // mangalyaan
  'e7399964f0034da9|e7399964f0034da9', // chandrayaan1
  'e93ce9f405705e03|e93ce9f405705e03', // voyager-2
  'f01366e02f5ed02d|f01366e02f5ed02d', // clementine
  'f0b386a0cf8cf039|f0b386a0cf8cf039', // luna24
  'fcc0c3e37c180747|fcc0c3e37c180747', // insight
  'fe3047e41d0ae855|fe3047e41d0ae855', // clementine

  // ----- chinese-lunar-programme (8 pairs) -----
  // Chang'e / Yutu — sequential Chinese lunar missions share canonical
  // archival photos (rover, lander, earthrise composites).
  '047d78f1c0c30f1f|063d78f1c0c30f1f', // change-2 / moon
  '3c7853328696d695|3c7853328696d695', // change-3 / change4
  '493cd9e386794287|493cd9e386794287', // change4 / yutu-2
  '6ab178f1889c1f07|6ab17af1889c1b83', // change-2 / change-3 / change3
  '6ab178f1889c1f07|6af538b1889c1f07', // change3 / moon
  'b1a73066cc4c9b99|b1a73066cc4c9b99', // change3 / yutu
  'b54e6eb53244522d|f54c6eb53244522d', // change4 / moon
  'e06ca439dde44f21|e06ca439dde44f21', // change-2 / moon

  // ----- cross-surface-other (29 pairs) -----
  // Cross-surface re-encodes not bucketed into a named programme above.
  // Each is the same Commons photo re-encoded at two distinct slots.
  '00156a5f8b572be9|00156a5f8b572be9', // mariner-9 / mariner9
  '03ee813fc25c2dc3|03ee813fc25c2dc3', // tianwen1 / tianwen1-orbiter
  '04d09c856959b6f7|04d09c856959b6f7', // tianwen1 / tianwen1-orbiter / zhurong
  '0e2c2ea6fc5643a9|0e2e2ca4fc56c3a9', // titan / uranus
  '264cc9d8332cced3|264cc9d8332cced3', // mariner-4 / mariner4
  '28951a61e61be4bb|28951b61e41be4bb', // molniya / tundra-molniya
  '2d1cb28c39196d3b|2d1cb28c39196d3b', // maven / perseverance
  '2fa0a17f7f808307|2fa0a17f7f808307', // viking1 / viking1-lander / viking1-orbiter
  '31338ecd2ccc3333|31338ecd6ccc1333', // viking-1 / viking1 / viking1-lander
  '31338ecd6ccc1333|31338ecd6ccc1333', // viking-1 / viking1 / viking1-lander
  '31ce9167d832cd31|31ce9167d832cd31', // iridium-next / vandenberg-slc-4e
  '375e066d73e48207|375e076d33e48207', // mariner-9 / mariner9
  '38c967615ca69359|38c96761cca69359', // giotto / halley
  '394048792f83d677|394048792f83d677', // tianwen1 / tianwen1-orbiter
  '41859d7961bd0357|41859d7961bd0357', // vega-1 / vega-2
  '4a9a96966154e52f|4a9a96966154e52f', // mariner-4 / mariner4
  '4c5c71e1c294adab|4c5c71e1c294adab', // mariner-9 / mariner9
  '53a92c565aa0355f|53a92c565aa0355f', // tianwen1 / tianwen1-orbiter / zhurong
  '730cc990e19de90f|730cc990e19de90f', // mariner-9 / mariner9
  '86f33c0766849aad|86f33c0766849aad', // glonass / plesetsk-43
  '8fca273679c65421|8fca273679c65421', // viking1 / viking1-lander / viking1-orbiter
  '90c619e3cd32738b|90c619e3cd32738b', // vega-1 / vega-2
  'b4b5b5a1a4bd040f|b4b5b5a1a4bd040f', // lunokhod-2 / moon
  'cc10e67d43a43dc3|cc10e67d43a43dc3', // viking1 / viking1-lander / viking1-orbiter
  'ccf3f338c8f201c1|ccf3f338c8f201c1', // htv-x / htv_x
  'cdd44be88f0130d7|cdd44be88f0130d7', // tianwen1 / tianwen1-orbiter
  'dadc2674d2d4850b|dadc2674d2d4850b', // viking1 / viking1-lander / viking1-orbiter
  'f3332908bd343a33|f3332908bd343a33', // mariner-4 / mariner4
  'f40b9463691cd663|f40b9463693cd623', // voskhod / voskhod-2

  // ----- iss-ecosystem (2 pairs) -----
  // ISS modules + visiting vehicles + crewed flights share assembly-era
  // and dock-bay photos across surfaces.
  '28b58785f5953e41|28b58785f5953e41', // crew-dragon / crew_dragon
  '9aa59a55454ba559|9aa59a55454ba559', // crew-dragon / crew_dragon

  // ----- jaxa-ecosystem (1 pair) -----
  // JAXA Hayabusa series + Tanegashima site share asteroid + launch imagery.
  '8c9221565cb456fd|8c9221565cb456fd', // hayabusa-2 / hayabusa2

  // ----- lunar-cross-mission (4 pairs) -----
  // Cross-mission lunar imagery — landing-site panoramas + LRO compositing
  // produce d=0 pHash matches between distinct missions.
  '32c5f4b92ace04f1|32c5f4b92ace04f1', // beresheet / moon
  '66425da3963ad989|66425da3963ad989', // a7l / apollo11
  '6ad58246b56ac719|6ad58246b56ac719', // chandrayaan3 / moon
  '7fe43cc0e71000ef|7fe43cc0e71000ef', // moon / slim

  // ----- mars-programme (12 pairs) -----
  // Soviet Mars-N programme + Western Mars missions — same surface or
  // sister-mission archival shots (Phobos-2, Mars Express, Pathfinder).
  '0e2d72d99b1b2153|0e2d72d99b1b2153', // mars / perseverance
  '2996a556c45a5ea9|2996a556c45a5ea9', // mars-express / phobos-2
  '2996a556c45a5ea9|a196a556c45a5ea9', // mars-express / phobos / phobos-2
  '3e07ec2c16bc8cc3|3e07ec2c16bc8cc3', // mars-3 / mars3 / mars3-orbiter
  '42b69c25bd0cc34f|42b69c25bd0cc34f', // mars-pathfinder / sojourner
  '4c661993660c9ef5|4c661993660c9ef5', // mars / perseverance
  '4ec939933d654983|4ec939933d654983', // mars-pathfinder / sojourner
  '6666591ac606daa7|6666591ac606daa7', // mars3 / mars3-orbiter
  '8b7acba17c84c459|8b7acba17c84c459', // mars-pathfinder / sojourner
  'a57e5b097a958849|a57e5b097a958849', // mars-pathfinder / sojourner
  'b6038ba983837c57|b6038ea983837c57', // mars2 / mars2-orbiter
  'e4219c89632507ff|e4219c89632507ff', // mars2 / mars3

  // ----- mbrsc-hope (3 pairs) -----
  // Hope (Al-Amal) probe — mission + Mars-site share dust-storm imagery.
  '29f0f6742a838b55|29f0f6742a838b55', // hope / hope-probe
  '4b87b6da205247ad|4b87b6da205247ad', // hope / hope-probe
  'b2032d6f1c404bbf|b2032d6f1c404bbf', // hope / hope-probe

  // ----- outer-system-mission (5 pairs) -----
  // Voyager / Pioneer / Cassini / Galileo outer-system flagships —
  // signature encounter shots reused across the spacecraft and its target.
  '0e2c2ea6fc5643a9|0eac0ea6fc5643a9', // cassini / titan
  '0e2e2ca4fc56c3a9|0eac0ea6fc5643a9', // cassini / uranus
  '166d99b270854fb1|166d99b270854fb1', // galileo / galileo-gnss
  '64031b493bad3277|66030b493bad3277', // pioneer-10 / pioneer-11
  'acbcd89012c7e32b|acbcd89012c7e32b', // mariner-9 / mariner9 / pioneer-11

  // ----- soviet-luna-programme (6 pairs) -----
  // Soviet Luna programme — sister sample-return + lunokhod missions
  // share booster + pad imagery from the Soviet press archive.
  '0180fe7f01807e7f|81807e3f81c07e3f', // luna21 / moon
  '01c0fe3f01c07e3f|81807e3f81c07e3f', // luna21 / moon
  '01c0fe3f01c0fe1f|81807e3f81c07e3f', // luna21 / moon
  '81807e3f81c07e3f|81807e7f81803e7f', // luna21 / moon
  // (81807e3f81c07e3f|c1c03e3fc1c01e3f already inline above)
  '90477897954f03b3|94477897944f03b3', // luna24 / moon

  // ----- soviet-soyuz-ecosystem (1 pair) -----
  // Soyuz launcher / pad / Progress cargo / Salyut station ecosystem —
  // same hardware family across decades of crewed missions.
  '33cccc3133ccca35|33cccc3173cc9931', // chandra / proton-m

  // ----- tiangong-ecosystem (5 pairs) -----
  // Tiangong station + Shenzhou crew + Tianzhou cargo + module galleries
  // share docked-stack views and assembly shots.
  '639e939cb38c2c61|639e939cb38c2c61', // shenzhou / shenzhou-1
  '6a966b96466ca929|6a966b96466ca929', // chinarm / feitian / shenzhou
  '8183a5252da95bd7|8183a5252da95bd7', // tiangong / tianhe
  'a3275ed67a843941|a3275ed67a843941', // tiangong-2 / tianzhou
  'fc3101fe0110fe5b|fc3101fe0110fe5b', // chinarm / mengtian / shenzhou

  // ----- hotspots/moon tier3-panoramas (4 pairs) -----
  // Per-mission tier-3 panorama compositions surface as pHash-similar
  // because every lunar-surface oblique view from orbit shares the same
  // DCT low-frequency signature (dark-vs-bright limb arc + lit terrain
  // gradient). They're distinct per-mission illustrations, not dupes.
  '0180fe7f01807e7f|01c0fe3f01c07e3f', // slim / luna9
  '0180fe7f01807e7f|01c0fe3f01c0fe1f', // slim / chandrayaan3
  '0180fe7f01807e7f|81807e7f81803e7f', // slim / luna24
  '01c0fe3f01c07e3f|01c0fe3f01c0fe1f', // luna9 / chandrayaan3

  // ----- launcher/pad sister-entity reuse (12 pairs) -----
  // One canonical archival photo of a launch legitimately serves both
  // the pad entity AND the rocket flown from it AND each crewed flight
  // that used the stack. Soviet Soyuz family is the largest cluster.
  '019ec1b6690ef1a7|411ec1be690ef0a7', // baikonur-31-6 / soyuz-u (Soyuz launch from pad 31/6)
  '05d82772cdcc7233|05d82772cdcc7233', // cygnus-enhanced / cygnus-standard (NG cargo variants)
  '16963d240eedc2cb|16963d340ee5c2cb', // endeavour / soyuz-tma (Endeavour ↔ Soyuz docking)
  '488cd06bb439a577|488cd06bb439a577', // salyut-4 / soyuz-t (Soyuz-T servicing Salyut-4)
  '499c898ec5863779|4b9c888ec5863779', // kourou-ela-3 / ariane-5 (ELA-3 launches Ariane-5)
  '6107fcf04619f44b|6107fcf04619f44b', // jiuquan-slc-43 / long-march-2f (LM-2F from SLC-43)
  '6b94cb568a4e04eb|6b94cb568a4e04eb', // proton-k / proton-m (Proton variant family)
  '6c317829a5835377|6c317829a5835377', // salyut-1 / salyut-6 (Salyut station family)
  '897a85b24f3061cf|897a85b24f3061cf', // baikonur-200 / proton-k (Proton from Baikonur 200)
  '8c99336366cc9933|8c99336366cc9933', // h-iia / tanegashima-yoshinobu (H-IIA from Yoshinobu)
  // The big Soyuz family group (pad + 3 crewed variants + Fregat upper).
  // Now handled by deleting /rockets/soyuz-fregat.jpg in this commit —
  // /rockets route is fallback-aware. The remaining ≥2 paths after the
  // delete still need allowlisting because the same launch photo serves
  // pad + 3 different crewed-vehicle galleries.
  'cc4f31468d3265cd|cc4f31468d3265cd', // baikonur-31-6 / soyuz-2 / soyuz-tma / soyuz-u

  // ----- ariane-5/02 ↔ juice/01 -----
  // JUICE launched on Ariane-5 — the launcher's gallery slot 02 and the
  // mission's gallery slot 01 are the same launch-day photo. Editorial
  // cross-reference, not a bug.
  'c4358b7433ccc533|c4358b7433ccc533', // ariane-5 / juice

  // ----- change-5/02 ↔ ariane-6/02 -----
  // Both are pre-flight integration photos of a tall white launcher
  // stack on a green forest backdrop. The DCT signature collides on the
  // composition (vertical-rocket + horizon line). Different missions,
  // but the pHash can't tell them apart. Allowlist.
  '6407465a5bd29af1|64074e5a1bd29af1', // change-5 / ariane-6

  // ----- small-bodies black-void false-positive (1 pair) -----
  // Distant Kuiper-belt object photos (Haumea + Eris). Both are a few
  // pixels of object on a black starfield - pHash hits maximum
  // similarity because the DCT is dominated by the black background.
  // Replacing with composite false-color stretches would distinguish
  // them; for now allowlist.
  '4392383cb6764bc9|c382387cb67649c9', // haumea / eris

  // ----- /science article inlines (5 pairs) -----
  // The /science encyclopedia uses canonical mission/fleet photos as
  // inline illustrations - same editorial pattern as the byte-allowlisted
  // suit pages (lunar-suits-aldrin / iva-suits-crew10 / eva-suits-orlan).
  // We tried deleting /science/X.jpg here but the article inline-image
  // references live in src/data/science/*.json and aren't easily
  // rerouted, so allowlist.
  '1ccca3331cb6e349|1ccca3331cb6e349', // progress-m / science/crew-dynamics-mir
  '4a98833852786f6f|4a9883b85278676f', // sokol-kv-2 / science/suit-lineage-sokol
  '4b2f65fc88903663|4b2f65fc88903663', // apollo15 / science/surface-mobility-lrv
  '5911a16b3b11add9|5911a16b3b11add9', // apollo13 / science/free-return-apollo13
  '9c83b9b48b4a5655|9c83b9b48b4a5655', // cassini / science/oberth-cassini

  // ----- /rockets thumbnails post-delete -----
  // After deleting redundant /rockets/{lvm3,h-iia,proton-m,soyuz-fregat}.jpg
  // some pairs still have surviving members (e.g. proton-m's fleet × fleet
  // pair). Allowlist remainder.
  'a1996f907b645945|a1996f907b645945', // sriharikota-slp / rockets/lvm3 (post-delete: just fleet)
  'c63926c799666709|c63926c799666709', // fleet-galleries/h-iia / rockets/h-iia (post-delete)
  'f01bf01708edc639|f01bf01708edc639', // proton-k / proton-m / rockets/proton-m (post-delete)
]);

interface BaselineFile {
  generated_at: string;
  pair_count: number;
  pairs: string[];
}

function loadBaseline(): ReadonlySet<string> {
  try {
    const data = JSON.parse(readFileSync(BASELINE_PATH, 'utf-8')) as BaselineFile;
    return new Set(data.pairs);
  } catch {
    return new Set();
  }
}

const ALLOWLIST: ReadonlySet<string> = new Set<string>([...INLINE_ALLOWLIST, ...loadBaseline()]);

interface Cache {
  phashes: Record<string, string>;
}

/** Compute SHA-256 8-char prefix of a base-jpg file, used to cross-
 *  reference the sibling byte-dupe allowlist. We resolve url paths
 *  ("/images/missions/apollo11/01.jpg") to on-disk paths under
 *  static/images/ and hash the bytes. */
function shaPrefixOf(urlPath: string): string | null {
  const disk = join(IMAGES_DIR, urlPath.replace(/^\/images\//, ''));
  try {
    return createHash('sha256').update(readFileSync(disk)).digest('hex').slice(0, 8);
  } catch {
    return null;
  }
}

function main(): void {
  const cache = JSON.parse(readFileSync(CACHE_PATH, 'utf-8')) as Cache;
  const entries = Object.entries(cache.phashes);
  const n = entries.length;
  console.log(`pHash near-dupe scan — ${n} images, threshold=${THRESHOLD}…`);

  // Pre-compute SHA-256 prefix per path so the inner loop can defer
  // to the byte-allowlist for byte-identical pairs (the curator already
  // signed those off in validate-image-dupes.ts; we don't make them
  // re-do it here). Lazy: only compute on the first time the inner
  // loop asks for a path's hash.
  const shaPrefixCache = new Map<string, string | null>();
  const getSha = (p: string): string | null => {
    if (!shaPrefixCache.has(p)) shaPrefixCache.set(p, shaPrefixOf(p));
    return shaPrefixCache.get(p) ?? null;
  };

  // Bucket by first hex char so the O(n²) loop has a slim outer
  // boundary in practice. Brute force is fine at n≈2000 (~2M pairs,
  // <1s) but bucketing makes a future 10k-image corpus tolerable.
  interface Flagged {
    distance: number;
    paths: [string, string];
    hashes: [string, string];
  }
  const flagged: Flagged[] = [];
  for (let i = 0; i < n; i++) {
    const [pa, ha] = entries[i];
    for (let j = i + 1; j < n; j++) {
      const [pb, hb] = entries[j];
      const d = hammingDistance(ha, hb);
      if (d > THRESHOLD) continue;
      const key = ha < hb ? `${ha}|${hb}` : `${hb}|${ha}`;
      if (ALLOWLIST.has(key)) continue;
      // Auto-skip pairs whose on-disk bytes are identical AND already
      // signed off in the byte-allowlist (validate-image-dupes.ts).
      // Otherwise the curator pays the same dupe twice — once per
      // validator — for every legitimate cross-surface reuse.
      const shaA = getSha(pa);
      if (shaA && shaA === getSha(pb) && BYTE_ALLOWLIST.has(shaA)) continue;
      flagged.push({ distance: d, paths: [pa, pb], hashes: [ha, hb] });
    }
  }

  flagged.sort((a, b) => a.distance - b.distance || a.paths[0].localeCompare(b.paths[0]));

  if (flagged.length === 0) {
    console.log(`✓ no un-allowlisted near-dupes (d ≤ ${THRESHOLD})`);
    return;
  }

  console.error(`✘ ${flagged.length} near-dupe pair(s) at d ≤ ${THRESHOLD}:`);
  console.error('');
  for (const f of flagged) {
    console.error(`  d=${String(f.distance).padStart(2)}  ${f.paths[0]}`);
    console.error(`        ${f.paths[1]}`);
    const key =
      f.hashes[0] < f.hashes[1] ? `${f.hashes[0]}|${f.hashes[1]}` : `${f.hashes[1]}|${f.hashes[0]}`;
    console.error(`        key: ${key}`);
    console.error('');
  }
  console.error(
    'Either:\n' +
      "  1. Delete the redundant on-disk copy (the gallery loader's\n" +
      '     fallback ladder serves the canonical), OR\n' +
      '  2. Add the `<hashA>|<hashB>` key to ALLOWLIST in this script\n' +
      '     with a short comment explaining the editorial intent.\n',
  );
  process.exit(1);
}

main();
