/**
 * Gallery-URL builders + hero-override orchestration, extracted from the data
 * client per ADR-084 §constraints (no business logic in the client).
 */

import { get } from './core';
import { assetOrigin } from '../asset-url';
import { loadHeroOverrides, applyHeroOverride } from '$lib/image-hero';

/**
 * Hand-curated aliases for cases where a site id and its gallery's
 * curated id are semantically related but not derivable by
 * normalization. Add cautiously — only when a real gallery exists
 * under a name that wouldn't be reached by the variant generator.
 */
const GALLERY_ID_ALIASES: Record<string, string> = {
  // Luna 21's surface mission was the Lunokhod 2 rover; the gallery
  // under fleet-galleries/lunokhod-2/ is the right surface imagery
  // for the luna21 site, but neither "luna21" nor "luna-21" derives
  // from "lunokhod-2" by id-variant rules.
  luna21: 'lunokhod-2',
};

/**
 * Generate id-variants to probe across manifests with inconsistent
 * naming conventions. fleet-galleries.json was hand-curated with
 * dash-separated names ("viking-1", "luna-16"); mission-galleries
 * and site-id conventions tend toward no-dash ("viking1", "luna16",
 * with site ids sometimes carrying a "-lander" / "-orbiter" suffix).
 * Try every reasonable form so a single canonical-id callsite hits
 * whatever the manifests happen to have.
 *
 * Examples:
 *   viking1-lander → [viking1-lander, viking1, viking-1, viking-1-lander]
 *   luna16          → [luna16, luna-16]
 *   change5         → [change5, change-5]
 */
function gallerySiteIdVariants(id: string): string[] {
  const variants = new Set<string>([id]);
  const stripped = id.replace(/-(lander|orbiter|rover)$/, '');
  if (stripped !== id) variants.add(stripped);
  // Insert a dash before trailing digits. "viking1" → "viking-1".
  for (const candidate of [id, stripped]) {
    const dashed = candidate.replace(/^([a-z]+)(\d+)$/, '$1-$2');
    if (dashed !== candidate) variants.add(dashed);
  }
  // Hand-curated alias (e.g. luna21 → lunokhod-2).
  if (GALLERY_ID_ALIASES[id]) variants.add(GALLERY_ID_ALIASES[id]);
  return Array.from(variants);
}

/** Venus sites have no image galleries yet — returns an empty set. */
export async function getVenusSiteGallery(): Promise<string[]> {
  return [];
}

/**
 * ISS module photo gallery URLs (manifest `iss-galleries.json`). Empty when
 * count is 0 — UI hides the GALLERY tab.
 */
export async function getIssModuleGallery(moduleId: string): Promise<string[]> {
  return getCategoryGallery('iss-modules', 'iss-galleries.json', moduleId);
}

export async function getTiangongModuleGallery(moduleId: string): Promise<string[]> {
  return getCategoryGallery('tiangong-modules', 'tiangong-galleries.json', moduleId);
}

/**
 * Fleet entry photo gallery URLs. Returns empty array when the entry
 * has no gallery yet — UI hides the GALLERY tab in that case. Manifest
 * `fleet-galleries.json` is generated by `fetch-assets.ts` in Phase D.
 */
export async function getFleetGallery(id: string): Promise<string[]> {
  try {
    const map = await get<Record<string, number>>('fleet-galleries.json').catch(() => null);
    if (!map) return [];
    const count = map[id] ?? 0;
    if (count === 0) return [];
    const gallery = Array.from(
      { length: count },
      (_, i) =>
        `${assetOrigin}/images/fleet-galleries/${id}/${String(i + 1).padStart(2, '0')}.webp`,
    );
    // Honour the fleet hero-override JSON so the panel hero (gallery[0])
    // matches the card cover served via pickHero('fleet', id). Without
    // this the audit-blessed slot reaches /fleet cards but the detail
    // panel still surfaces the unblessed slot 01.
    await loadHeroOverrides('fleet');
    return applyHeroOverride('fleet', id, gallery);
  } catch {
    return [];
  }
}

/**
 * Mission photo gallery (v0.1.8). Returns the list of image URLs for
 * a mission's gallery tab. Manifest at
 * `static/data/mission-galleries.json` is generated at build by
 * `scripts/fetch-assets.ts` (NASA Images API + Wikimedia fallback).
 *
 * Returns an empty array when no gallery exists for the mission —
 * the UI hides the gallery tab in that case.
 */
export async function getMissionGallery(missionId: string): Promise<string[]> {
  try {
    const map = await get<Record<string, number>>('mission-galleries.json');
    const count = map[missionId] ?? 0;
    if (count === 0) return [];
    const gallery = Array.from(
      { length: count },
      (_, i) =>
        `${assetOrigin}/images/missions/${missionId}/${String(i + 1).padStart(2, '0')}.webp`,
    );
    // Honour the mission hero-override JSON so the panel hero (gallery[0])
    // matches the card cover served via pickHero('missions', id). Without
    // this the audit-blessed slot reaches /missions cards but the detail
    // panel still surfaces the unblessed slot 01 (perseverance is the
    // canonical example — 01.jpg is a mis-sourced Curiosity photo).
    await loadHeroOverrides('missions');
    return applyHeroOverride('missions', missionId, gallery);
  } catch {
    return [];
  }
}

/**
 * Generic photo-gallery loader (v0.1.10). Mirrors getMissionGallery
 * for planets, the sun, earth-objects, and moon-sites — every panel
 * with a GALLERY tab uses the same manifest pattern.
 *
 * @param category — "planets" | "earth-objects" | "moon-sites" | "small-bodies" (image folder root)
 * @param manifestFile — name of the per-category manifest JSON (e.g. "planet-galleries.json")
 * @param id — entity id (planet name lowercased, earth-object id, moon-site id)
 *
 * Returns an empty array when no images exist — the UI hides the
 * GALLERY tab in that case.
 */
async function getCategoryGallery(
  category: string,
  manifestFile: string,
  id: string,
): Promise<string[]> {
  try {
    const map = await get<Record<string, number>>(manifestFile);
    const count = map[id] ?? 0;
    if (count === 0) return [];
    return Array.from(
      { length: count },
      (_, i) => `${assetOrigin}/images/${category}/${id}/${String(i + 1).padStart(2, '0')}.webp`,
    );
  } catch {
    return [];
  }
}

export async function getPlanetGallery(planetId: string): Promise<string[]> {
  const gallery = await getCategoryGallery('planets', 'planet-galleries.json', planetId);
  if (gallery.length === 0) return gallery;
  // Honour the planets hero-override JSON so the panel hero (gallery[0])
  // matches the card cover served via pickHero('planets', id). Mirrors
  // the fleet / missions pattern.
  await loadHeroOverrides('planets');
  return applyHeroOverride('planets', planetId, gallery);
}

export async function getSunGallery(): Promise<string[]> {
  // Sun is a single entity — use a flat count manifest.
  try {
    const data = await get<{ count: number }>('sun-gallery.json');
    const count = data.count ?? 0;
    if (count === 0) return [];
    return Array.from(
      { length: count },
      (_, i) => `${assetOrigin}/images/sun/${String(i + 1).padStart(2, '0')}.webp`,
    );
  } catch {
    return [];
  }
}

export async function getEarthObjectGallery(
  objectId: string,
  missionIdFallback?: string,
): Promise<string[]> {
  const own = await getCategoryGallery('earth-objects', 'earth-object-galleries.json', objectId);
  if (own.length > 0) return own;
  // Fallback: many earth-objects (LRO, Hubble, JWST, ISS, etc.) match
  // a mission id with an existing photo gallery. Use those photos so
  // every panel gets meaningful imagery without re-vendoring.
  const fallbackId = missionIdFallback ?? objectId;
  return getMissionGallery(fallbackId);
}

export async function getMoonSiteGallery(
  siteId: string,
  missionIdFallback?: string,
): Promise<string[]> {
  // Same fallback ladder as getMarsSiteGallery (#PE 2026-05-22) —
  // per-site override → mission-gallery (by mission_id then site id)
  // → fleet-gallery (by every id-variant). Captures the cases where
  // lunar surface missions (e.g. Surveyor-class, early Luna landers,
  // Chang'e 3/4) have images only in fleet-galleries.json under
  // dash-separated ids like "luna-16" while site ids use "luna16".
  // Final step: respect the moon-sites hero override JSON (#5 Phase 5+)
  // so the audit-blessed slot becomes the gallery hero.
  await loadHeroOverrides('moon-sites');
  const reorder = (g: string[]) => applyHeroOverride('moon-sites', siteId, g);
  const own = await getCategoryGallery('moon-sites', 'moon-site-galleries.json', siteId);
  if (own.length > 0) return reorder(own);
  if (missionIdFallback) {
    const byMission = await getMissionGallery(missionIdFallback);
    if (byMission.length > 0) return reorder(byMission);
  }
  const bySite = await getMissionGallery(siteId);
  if (bySite.length > 0) return reorder(bySite);
  if (missionIdFallback) {
    for (const v of gallerySiteIdVariants(missionIdFallback)) {
      const g = await getFleetGallery(v);
      if (g.length > 0) return reorder(g);
    }
  }
  for (const v of gallerySiteIdVariants(siteId)) {
    const g = await getFleetGallery(v);
    if (g.length > 0) return reorder(g);
  }
  return [];
}

/**
 * /explore small-body panel (dwarfs, comets, interstellar). Manifest
 * `small-body-galleries.json` + `static/images/small-bodies/{id}/`
 * from `npm run fetch-assets`.
 */
export async function getSmallBodyGallery(bodyId: string): Promise<string[]> {
  const gallery = await getCategoryGallery('small-bodies', 'small-body-galleries.json', bodyId);
  if (gallery.length === 0) return gallery;
  // Honour the small-bodies hero-override JSON — mirrors the planets/fleet pattern.
  await loadHeroOverrides('small-bodies');
  return applyHeroOverride('small-bodies', bodyId, gallery);
}

export async function getSatelliteGallery(satelliteId: string): Promise<string[]> {
  const gallery = await getCategoryGallery('satellites', 'satellite-galleries.json', satelliteId);
  if (gallery.length === 0) return gallery;
  // Honour the satellites hero-override JSON — mirrors the planets/fleet pattern.
  await loadHeroOverrides('satellites');
  return applyHeroOverride('satellites', satelliteId, gallery);
}

/** Belt gallery (asteroid + kuiper). Reads belt-galleries.json which
 *  was reshaped 2026-06-21 from { galleries: { asteroid: [{src,caption}] } }
 *  to a flat { asteroid: N, kuiper: N } count map matching the other
 *  gallery manifests. Images live under static/images/belts/<beltId>/ */
export async function getBeltGallery(beltId: string): Promise<string[]> {
  return getCategoryGallery('belts', 'belt-galleries.json', beltId);
}

/**
 * Mars site gallery loader. Multi-tier fallback so /mars detail panels
 * surface SOMETHING from every available image manifest before falling
 * silent. Order: per-site override → mission-gallery (by mission_id
 * AND by site id) → fleet-gallery (by mission_id AND by site id),
 * with id-normalization at every fleet probe.
 *
 * Why all the steps: the existing image inventory is split across
 * three manifests (mars-site-galleries.json, mission-galleries.json,
 * fleet-galleries.json) due to historical capture pipelines. Some
 * Mars hotspot sites (spirit, opportunity, phoenix, schiaparelli,
 * zhurong) only have images in fleet-galleries.json; others
 * (curiosity, perseverance) are in mission-galleries.json. Walking
 * all lookups gives us coverage today without an asset
 * re-organization pass. #PE-mars (2026-05-22).
 */
export async function getMarsSiteGallery(
  siteId: string,
  missionIdFallback?: string,
): Promise<string[]> {
  // Mars hero overrides (#5 Phase 5+) — reorder so the audit-blessed
  // slot becomes first whenever a non-empty gallery is found.
  await loadHeroOverrides('mars-sites');
  const reorder = (g: string[]) => applyHeroOverride('mars-sites', siteId, g);
  // 1. Per-site override (preferred — currently empty manifest).
  const own = await getCategoryGallery('mars-sites', 'mars-site-galleries.json', siteId);
  if (own.length > 0) return reorder(own);
  // 2. Mission gallery by explicit mission_id, if set.
  if (missionIdFallback) {
    const byMission = await getMissionGallery(missionIdFallback);
    if (byMission.length > 0) return reorder(byMission);
  }
  // 3. Mission gallery by site id (site_id == mission_id case).
  const bySite = await getMissionGallery(siteId);
  if (bySite.length > 0) return reorder(bySite);
  // 4 + 5. Fleet gallery by mission_id and by every id-variant of
  // the site id (covers "luna16" vs "luna-16", "viking1-lander" vs
  // "viking-1" naming-convention drift).
  if (missionIdFallback) {
    for (const v of gallerySiteIdVariants(missionIdFallback)) {
      const g = await getFleetGallery(v);
      if (g.length > 0) return reorder(g);
    }
  }
  for (const v of gallerySiteIdVariants(siteId)) {
    const g = await getFleetGallery(v);
    if (g.length > 0) return reorder(g);
  }
  return [];
}
