/**
 * Universal SvelteKit hooks (run on both server + client).
 *
 * `reroute` strips the Paraglide locale prefix (`/de/missions`,
 * `/fr/iss`, …) so SvelteKit's router matches the bare path
 * (`/missions`, `/iss`) against the file-system routes. Without this,
 * every localized URL would 404 because there's no `/de/+page.svelte`.
 *
 * `deLocalizeUrl` is generated by paraglide-js from the URL strategy
 * config in vite.config.ts (`strategy: ['url', ...]`). Baseline
 * (en-US) URLs are already bare, so reroute is a no-op for them.
 */
import { deLocalizeUrl } from '$lib/paraglide/runtime';
import type { Reroute } from '@sveltejs/kit';

export const reroute: Reroute = (request) => deLocalizeUrl(request.url).pathname;
